-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/addons/handynotes-suramartelemancy/localization/

local myname, ns = ...

local L = LibStub("AceLocale-3.0"):NewLocale(myname, "deDE")
if not L then return end

L["Astravar Harbor"] = "Hafen der Astravar"
L["Evermoon Terrace"] = "Immermondterrasse"
L["Falanaar"] = "Falanaar"
L["Felsoul Hold"] = "Teufelsseelenbastion"
L["Lunastre Estate"] = "Anwesen der Lunastres"
L["Moon Guard (entrance)"] = "Mondwachenfestung (Eingang)"
L["Moon Guard Stronghold"] = "Mondwachenfestung"
L["Ruins of Elune'eth"] = "Ruinen von Elune'eth"
L["Sanctum of Order"] = "Sanktum der Ordnung"
L["Sanctum of Order (entrance)"] = "Sanktum der Ordnung (Eingang)"
L["Tel'anor"] = "Tel'anor"
L["Twilight Vineyards"] = "ZwielichtrebgÃ¤rten"
L["Waning Crescent"] = "Mondsichelforum"

