-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/addons/handynotes-suramartelemancy/localization/

local myname, ns = ...

local L = LibStub("AceLocale-3.0"):NewLocale(myname, "esMX")
if not L then return end

L["Falanaar"] = "Falanaar"
L["Felsoul Hold"] = "Bastion Almavil"
L["Lunastre Estate"] = "Dominios de Lunastre"
L["Moon Guard (entrance)"] = "Fuerte de Guardia Lunar (Entrada)"
L["Moon Guard Stronghold"] = "Fuerte de Guardia Lunar"
L["Ruins of Elune'eth"] = "Ruinas de Elune'eth"
L["Sanctum of Order"] = "Sagrario de la Orden"
L["Sanctum of Order (entrance)"] = "Sagrario de la Orden (Entrada)"
L["Tel'anor"] = "Tel'anor"
L["Twilight Vineyards"] = "ViÃ±edos del Crepusculo"
L["Waning Crescent"] = "Cuarto Menguante"
