-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/addons/handynotes-suramartelemancy/localization/

local myname, ns = ...

local L = LibStub("AceLocale-3.0"):NewLocale(myname, "frFR")
if not L then return end

L["Astravar Harbor"] = "Port d'Astravar"
L["Evermoon Terrace"] = "Terrasse de Sempiterlune"
L["Falanaar"] = "Falanaar"
L["Felsoul Hold"] = "Bastion Gangrâme"
L["Lunastre Estate"] = "Domaine Lunastre"
L["Moon Guard (entrance)"] = "Garde de la Lune (Entrée)"
L["Moon Guard Stronghold"] = "Bastion de la Garde de la Lune"
L["Ruins of Elune'eth"] = "Ruines d’Élune’eth"
L["Sanctum of Order"] = "Sanctum de l’Ordre"
L["Sanctum of Order (entrance)"] = "Sanctum de l’Ordre (Entrée)"
L["Tel'anor"] = "Tel’anor"
L["Twilight Vineyards"] = "Vignobles du Crépuscule"
L["Waning Crescent"] = "Lune descendante"

