-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/addons/handynotes-suramartelemancy/localization/

local myname, ns = ...

local L = LibStub("AceLocale-3.0"):NewLocale(myname, "itIT")
if not L then return end

L["Astravar Harbor"] = "Porto di Astravar"
L["Evermoon Terrace"] = "Terrazza di Lunavespro"
L["Falanaar"] = "Falanaar"
L["Felsoul Hold"] = "Forte Vilanima"
L["Lunastre Estate"] = "Tenuta dei Lunastra"
L["Moon Guard (entrance)"] = "Forte delle guardie della luna (entrata)"
L["Moon Guard Stronghold"] = "Forte delle guardie della luna"
L["Ruins of Elune'eth"] = "Rovine di Elune'eth"
L["Sanctum of Order"] = "Santuario dell'ordine"
L["Sanctum of Order (entrance)"] = "Santuario dell'ordine (entrata)"
L["Tel'anor"] = "Tel'anor"
L["Twilight Vineyards"] = "Vigne del crepuscolo"
L["Waning Crescent"] = "Mezzaluna Crescente"

