-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/addons/handynotes-suramartelemancy/localization/

local myname, ns = ...

local L = LibStub("AceLocale-3.0"):NewLocale(myname, "ptBR")
if not L then return end

L["Astravar Harbor"] = "Porto de Astravar"
L["Evermoon Terrace"] = "Terraco da Lua Perene"
L["Falanaar"] = "Falanaar"
L["Felsoul Hold"] = "Castelo Almavil"
L["Lunastre Estate"] = "Propriedade dos Lunastre"
L["Moon Guard (entrance)"] = "Guarda da Lua (Entrada)"
L["Moon Guard Stronghold"] = "Fortaleza da Guarda da Lua"
L["Ruins of Elune'eth"] = "Ruinas de Elune'eth"
L["Sanctum of Order"] = "Sacrario da Ordem"
L["Sanctum of Order (entrance)"] = "Sacrario da Ordem (Entrada)"
L["Tel'anor"] = "Tel'anor"
L["Twilight Vineyards"] = "Vinhedo do Crepusculo"
L["Waning Crescent"] = "Lua Minguante"

