-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/addons/handynotes-suramartelemancy/localization/

local myname, ns = ...

local L = LibStub("AceLocale-3.0"):NewLocale(myname, "ruRU")
if not L then return end

L["Astravar Harbor"] = "Порт Астравар"
L["Evermoon Terrace"] = "Терраса Вечной Луны"
L["Falanaar"] = "Фаланар"
L["Felsoul Hold"] = "Оплот Оскверненной Души"
L["Lunastre Estate"] = "Поместье Лунархов"
L["Moon Guard (entrance)"] = "Лунные стражи (Вход)"
L["Moon Guard Stronghold"] = "Лунные стражи"
L["Ruins of Elune'eth"] = "Руины Элуны"
L["Sanctum of Order"] = "Святилище порядка"
L["Sanctum of Order (entrance)"] = "Святилище порядка (Вход)"
L["Tel'anor"] = "Тел'анор"
L["Twilight Vineyards"] = "Сумеречные виноградники"
L["Waning Crescent"] = "Лунный полумрак"

