-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/projects/omen-threat-meter/localization/

-- Italian localization file
local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("Omen", "itIT")
if not L then return end

--[[Translation missing --]]
--[[ L["*Not in Party*"] = "*Not in Party*"--]] 
--[[Translation missing --]]
--[[ L["|cffff0000Error:|r Omen cannot use shake warning if you have turned on nameplates at least once since logging in."] = "|cffff0000Error:|r Omen cannot use shake warning if you have turned on nameplates at least once since logging in."--]] 
--[[Translation missing --]]
--[[ L["<Unknown>"] = "<Unknown>"--]] 
--[[Translation missing --]]
--[[ L["> Pull Aggro <"] = "> Pull Aggro <"--]] 
--[[Translation missing --]]
--[[ L["A collection of help pages"] = "A collection of help pages"--]] 
--[[Translation missing --]]
--[[ L["Alpha"] = "Alpha"--]] 
--[[Translation missing --]]
--[[ L["Always Show Self"] = "Always Show Self"--]] 
--[[Translation missing --]]
--[[ L["Always show your threat bar on Omen (ignores class filter settings), showing your bar on the last row if necessary"] = "Always show your threat bar on Omen (ignores class filter settings), showing your bar on the last row if necessary"--]] 
--[[Translation missing --]]
--[[ L["Ambience"] = "Ambience"--]] 
--[[Translation missing --]]
--[[ L["Animate Bars"] = "Animate Bars"--]] 
--[[Translation missing --]]
--[[ L["Attach to minimap"] = "Attach to minimap"--]] 
--[[Translation missing --]]
--[[ L["AUTO_SHOW/HIDE_NOTE"] = "Note: If you manually toggle Omen to show or hide, it will remain shown or hidden regardless of Auto Show/Hide settings until you next zone, join or leave a party or raid, or change any Auto Show/Hide settings."--]] 
--[[Translation missing --]]
--[[ L["Autocollapse"] = "Autocollapse"--]] 
--[[Translation missing --]]
--[[ L["Autocollapse Options"] = "Autocollapse Options"--]] 
--[[Translation missing --]]
--[[ L["Background Color"] = "Background Color"--]] 
--[[Translation missing --]]
--[[ L["Background Options"] = "Background Options"--]] 
--[[Translation missing --]]
--[[ L["Background Texture"] = "Background Texture"--]] 
--[[Translation missing --]]
--[[ L["Background Tile Size"] = "Background Tile Size"--]] 
--[[Translation missing --]]
--[[ L["Bar BG Color"] = "Bar BG Color"--]] 
--[[Translation missing --]]
--[[ L["Bar Height"] = "Bar Height"--]] 
--[[Translation missing --]]
--[[ L["Bar Inset"] = "Bar Inset"--]] 
--[[Translation missing --]]
--[[ L["Bar Label Options"] = "Bar Label Options"--]] 
--[[Translation missing --]]
--[[ L["Bar Settings"] = "Bar Settings"--]] 
--[[Translation missing --]]
--[[ L["Bar Spacing"] = "Bar Spacing"--]] 
--[[Translation missing --]]
--[[ L["Bar Texture"] = "Bar Texture"--]] 
--[[Translation missing --]]
--[[ L["Border Color"] = "Border Color"--]] 
--[[Translation missing --]]
--[[ L["Border Texture"] = "Border Texture"--]] 
--[[Translation missing --]]
--[[ L["Border Thickness"] = "Border Thickness"--]] 
--[[Translation missing --]]
--[[ L["Causes Omen to play a chosen sound effect"] = "Causes Omen to play a chosen sound effect"--]] 
--[[Translation missing --]]
--[[ L["Causes the entire game world to shake momentarily. This option only works if nameplates are turned off."] = "Causes the entire game world to shake momentarily. This option only works if nameplates are turned off."--]] 
--[[Translation missing --]]
--[[ L["Causes the entire screen to flash red momentarily"] = "Causes the entire screen to flash red momentarily"--]] 
--[[Translation missing --]]
--[[ L["Center"] = "Center"--]] 
--[[Translation missing --]]
--[[ L["Center Omen"] = "Center Omen"--]] 
--[[Translation missing --]]
--[[ L["Clamp To Screen"] = "Clamp To Screen"--]] 
--[[Translation missing --]]
--[[ L["Click Through"] = "Click Through"--]] 
--[[Translation missing --]]
--[[ L["Click|r to toggle the Omen window"] = "Click|r to toggle the Omen window"--]] 
--[[Translation missing --]]
--[[ L["Collapse to show a minimum number of bars"] = "Collapse to show a minimum number of bars"--]] 
--[[Translation missing --]]
--[[ L["Configure"] = "Configure"--]] 
--[[Translation missing --]]
--[[ L["Configure bar settings."] = "Configure bar settings."--]] 
--[[Translation missing --]]
--[[ L["Configure title bar settings."] = "Configure title bar settings."--]] 
--[[Translation missing --]]
--[[ L["Control the font size of the labels"] = "Control the font size of the labels"--]] 
--[[Translation missing --]]
--[[ L["Control the font size of the title text"] = "Control the font size of the title text"--]] 
--[[Translation missing --]]
--[[ L["Controls the frame strata of the main Omen window. Default: MEDIUM"] = "Controls the frame strata of the main Omen window. Default: MEDIUM"--]] 
--[[Translation missing --]]
--[[ L["Controls the scaling of the main Omen window."] = "Controls the scaling of the main Omen window."--]] 
--[[Translation missing --]]
--[[ L["Controls the transparency of the main Omen window."] = "Controls the transparency of the main Omen window."--]] 
--[[Translation missing --]]
--[[ L["Controls whether the main Omen window can be dragged offscreen"] = "Controls whether the main Omen window can be dragged offscreen"--]] 
--[[Translation missing --]]
--[[ L["DEATHKNIGHT"] = "Death Knight"--]] 
--[[Translation missing --]]
--[[ L["DEMONHUNTER"] = "Demon Hunter"--]] 
--[[Translation missing --]]
--[[ L["Disable while tanking"] = "Disable while tanking"--]] 
--[[Translation missing --]]
--[[ L["DISABLE_WHILE_TANKING_DESC"] = "Do not give out any warnings if Defensive Stance, Bear Form, Righteous Fury or Blood Presence is active."--]] 
--[[Translation missing --]]
--[[ L["Display large numbers in Ks"] = "Display large numbers in Ks"--]] 
--[[Translation missing --]]
--[[ L["DRUID"] = "Druid"--]] 
--[[Translation missing --]]
--[[ L["Enable Screen Flash"] = "Enable Screen Flash"--]] 
--[[Translation missing --]]
--[[ L["Enable Screen Shake"] = "Enable Screen Shake"--]] 
--[[Translation missing --]]
--[[ L["Enable Sound"] = "Enable Sound"--]] 
--[[Translation missing --]]
--[[ L["Enable Warning Message"] = "Enable Warning Message"--]] 
--[[Translation missing --]]
--[[ L["FAQ Part 1"] = "FAQ Part 1"--]] 
--[[Translation missing --]]
--[[ L["FAQ Part 2"] = "FAQ Part 2"--]] 
--[[Translation missing --]]
--[[ L["Font"] = "Font"--]] 
--[[Translation missing --]]
--[[ L["Font Color"] = "Font Color"--]] 
--[[Translation missing --]]
--[[ L["Font Outline"] = "Font Outline"--]] 
--[[Translation missing --]]
--[[ L["Font Size"] = "Font Size"--]] 
--[[Translation missing --]]
--[[ L["Frame Strata"] = "Frame Strata"--]] 
--[[Translation missing --]]
--[[ L["Frame's background color"] = "Frame's background color"--]] 
--[[Translation missing --]]
--[[ L["Frame's border color"] = "Frame's border color"--]] 
--[[Translation missing --]]
--[[ L["Frequently Asked Questions"] = "Frequently Asked Questions"--]] 
--[[Translation missing --]]
--[[ L["FuBar Options"] = "FuBar Options"--]] 
--[[Translation missing --]]
--[[ L["General Settings"] = "General Settings"--]] 
--[[Translation missing --]]
--[[ L["GENERAL_FAQ"] = [=[
|cffffd200How is Omen3 different from Omen2?|r

Omen3 relies completely on the Blizzard threat API and threat events. It does not attempt to calculate or extrapolate threat unlike Omen2.

Omen2 used what we called the Threat-2.0 library. This library was responsible for monitoring the combat log, spellcasting, buffs, debuffs, stances, talents and gear modifiers for calculating each individuals threat. Threat was calculated based on what was known or approximated from observed behaviors. Many abilities such as knockbacks were just assumed (to be a 50% threat reduction) as they were mostly impossible to confirm.

The Threat-2.0 library also included addon communication to broadcast your threat to the rest of the raid as long as they were also using Threat-2.0. This data was then used to provide a raid wide display of threat information.

Since patch 3.0.2, Omen no longer does any of these things and the need for a threat library is no longer necessary. Omen3 uses Blizzard's new in-built threat monitor to obtain exact values of every members threat. This means Omen3 has no need for synchronisation of data, combat log parsing or guessing, resulting in a significant increase in performance with regards to network traffic, CPU time and memory used. The implementation of boss modules for specific threat events (such as Nightbane wiping threat on landing) are also no longer necessary.

Further benefits of this new implementation include the addition of NPC threat on a mob (eg, Human Kalecgos). However, there are some drawbacks; frequency of updates are much slower, threat details cannot be obtained unless somebody in your party/raid are targetting the mob and it is also not possible to obtain threat from a mob you are not in direct combat with.

|cffffd200How do I get rid of the 2 vertical gray lines down the middle?|r

Lock your Omen. Locking Omen will prevent it from being moved or resized, as well as prevent the columns from being resized. If you haven't realized it, the 2 vertical gray lines are column resizing handles.

|cffffd200How do I make Omen3 look like Omen2?|r

Change the both the Background Texture and Border Texture to Blizzard Tooltip, change the Background Color to black (by dragging the luminance bar to the bottom), and the Border Color to blue.

|cffffd200Why does no threat data show on a mob when I target it even though it is in combat?|r

The Blizzard threat API does not return threat data on any mob you are not in direct combat with. We suspect this is an effort on Blizzard's part to save network traffic.

|cffffd200Is there ANY way around this Blizzard limitation? Not being able to see my pet's threat before I attack has set me back to guessing.|r

There is no way around this limitation short of us doing the guessing for you (which is exactly how Omen2 did it).

The goal of Omen3 is to provide accurate threat data, we no longer intend to guess for you and in the process lower your FPS. Have some confidence in your pet/tank, or just wait 2 seconds before attacking and use a low damage spell such as Ice Lance so that you can get initial threat readings.
]=]--]] 
--[[Translation missing --]]
--[[ L["GENERAL_FAQ2"] = [=[|cffffd200Can we get AoE mode back?|r

Again, this is not really possible without guessing threat values. Blizzard's threat API only allows us to query for threat data on units that somebody in the raid is targetting. This means that if there are 20 mobs and only 6 of them are targetted by the raid, there is no way to obtain accurate threat data on the other 14.

This is also extremely complicated to guess particularly for healing and buffing (threat gets divided by the number of mobs you are in combat with) because mobs that are under crowd control effects (sheep, banish, sap, etc) do not have their threat table modified and addons cannot reliably tell how many mobs you are in combat with. Omen2's guess was almost always wrong.

|cffffd200The tooltips on unit mouseover shows a threat % that does not match the threat % reported by Omen3. Why?|r

Blizzard's threat percentage is scaled to between 0% and 100%, so that you will always pull aggro at 100%. Omen reports the raw unscaled values which has pulling aggro percentages at 110% while in melee range and 130% otherwise.

By universal agreement, the primary target of a mob is called the tank and is defined to be at 100% threat.

|cffffd200Does Omen3 sync or parse the combat log?|r

No. Omen3 does not attempt to sync or parse the combat log. Currently there are no intentions to do so.

|cffffd200The threat updates are slow...|r

Omen3 updates the threat values you see as often as Blizzard updates the threat values to us.

In fact, Blizzard updates them about once per second, which is much faster than what Omen2 used to sync updates. In Omen2, you only transmitted your threat to the rest of the raid once every 3 seconds (or 1.5s if you were a tank).

|cffffd200Where can I report bugs or give suggestions?|r

http://forums.wowace.com/showthread.php?t=14249

|cffffd200Who wrote Omen3?|r

Xinhuan (Blackrock/Barthilas US Alliance) did.

|cffffd200Do you accept Paypal donations?|r

Yes, send to xinhuan AT gmail DOT com.
]=]--]] 
--[[Translation missing --]]
--[[ L["Grow bars upwards"] = "Grow bars upwards"--]] 
--[[Translation missing --]]
--[[ L["Heading background color"] = "Heading background color"--]] 
--[[Translation missing --]]
--[[ L["Heading BG Color"] = "Heading BG Color"--]] 
--[[Translation missing --]]
--[[ L["Height of each bar"] = "Height of each bar"--]] 
--[[Translation missing --]]
--[[ L["Height of the title bar. The minimum height allowed is twice the background border thickness."] = "Height of the title bar. The minimum height allowed is twice the background border thickness."--]] 
--[[Translation missing --]]
--[[ L["Help File"] = "Help File"--]] 
--[[Translation missing --]]
--[[ L["Hide minimap/FuBar icon"] = "Hide minimap/FuBar icon"--]] 
--[[Translation missing --]]
--[[ L["Hide Omen"] = "Hide Omen"--]] 
--[[Translation missing --]]
--[[ L["Hide Omen entirely if it collapses to show 0 bars"] = "Hide Omen entirely if it collapses to show 0 bars"--]] 
--[[Translation missing --]]
--[[ L["Hide Omen on 0 bars"] = "Hide Omen on 0 bars"--]] 
--[[Translation missing --]]
--[[ L["However, hide Omen if any of the following are true (higher priority than the above)."] = "However, hide Omen if any of the following are true (higher priority than the above)."--]] 
--[[Translation missing --]]
--[[ L["HUNTER"] = "Hunter"--]] 
--[[Translation missing --]]
--[[ L["Ignore Player Pets"] = "Ignore Player Pets"--]] 
--[[Translation missing --]]
--[[ L["IGNORE_PLAYER_PETS_DESC"] = [=[
Tells Omen to skip enemy player pets when determining which unit to display threat data on.

Player pets maintain a threat table when in |cffffff78Aggressive|r or |cffffff78Defensive|r mode and behave just like normal mobs, attacking the target with the highest threat. If the pet is instructed to attack a specific target, the pet still maintains the threat table, but sticks on the assigned target which by definition has 100% threat. Player pets can be taunted to force them to attack you.

However, player pets on |cffffff78Passive|r mode do not have a threat table, and taunt does not work on them. They only attack their assigned target when instructed and do so without any threat table.

When a player pet is instructed to |cffffff78Follow|r, the pet's threat table is wiped immediately and stops attacking, although it may immediately reacquire a target based on its Aggressive/Defensive mode.
]=]--]] 
--[[Translation missing --]]
--[[ L["Invert Bar/Text Colors"] = "Invert Bar/Text Colors"--]] 
--[[Translation missing --]]
--[[ L["Left"] = "Left"--]] 
--[[Translation missing --]]
--[[ L["Lock Omen"] = "Lock Omen"--]] 
--[[Translation missing --]]
--[[ L["Locks Omen in place and prevents it from being dragged or resized."] = "Locks Omen in place and prevents it from being dragged or resized."--]] 
--[[Translation missing --]]
--[[ L["MAGE"] = "Mage"--]] 
--[[Translation missing --]]
--[[ L["Makes the Omen window non-interactive"] = "Makes the Omen window non-interactive"--]] 
--[[Translation missing --]]
--[[ L["Master"] = "Master"--]] 
--[[Translation missing --]]
--[[ L["Max bars to show"] = "Max bars to show"--]] 
--[[Translation missing --]]
--[[ L["Max number of bars to show"] = "Max number of bars to show"--]] 
--[[Translation missing --]]
--[[ L["Music"] = "Music"--]] 
--[[Translation missing --]]
--[[ L["'My Bar' BG Color"] = "'My Bar' BG Color"--]] 
--[[Translation missing --]]
--[[ L["Name"] = "Name"--]] 
--[[Translation missing --]]
--[[ L["None"] = "None"--]] 
--[[Translation missing --]]
--[[ L["Omen Quick Menu"] = "Omen Quick Menu"--]] 
--[[Translation missing --]]
--[[ L["OMEN_DESC"] = "Omen is a lightweight threat meter that shows you the threat of mobs you are engaged in combat with. You can change how Omen looks and behaves, and configure different profiles for every of your characters."--]] 
--[[Translation missing --]]
--[[ L["OMEN_SLASH_DESC"] = "These buttons execute the same functions as the ones in the slash command /omen"--]] 
--[[Translation missing --]]
--[[ L["OMEN_WARNINGS_DESC"] = "This section allows you to customize when and how Omen notifies you if you are about to pull aggro."--]] 
--[[Translation missing --]]
--[[ L["Open Config"] = "Open Config"--]] 
--[[Translation missing --]]
--[[ L["Open Omen's configuration panel"] = "Open Omen's configuration panel"--]] 
--[[Translation missing --]]
--[[ L["Open the configuration dialog"] = "Open the configuration dialog"--]] 
--[[Translation missing --]]
--[[ L["Outline"] = "Outline"--]] 
--[[Translation missing --]]
--[[ L["PALADIN"] = "Paladin"--]] 
--[[Translation missing --]]
--[[ L["Passed %s%% of %s's threat!"] = "Passed %s%% of %s's threat!"--]] 
--[[Translation missing --]]
--[[ L["PET"] = "Pet"--]] 
--[[Translation missing --]]
--[[ L["Pet Bar Color"] = "Pet Bar Color"--]] 
--[[Translation missing --]]
--[[ L["Position"] = "Position"--]] 
--[[Translation missing --]]
--[[ L["PRIEST"] = "Priest"--]] 
--[[Translation missing --]]
--[[ L["Print a message to screen when you accumulate too much threat"] = "Print a message to screen when you accumulate too much threat"--]] 
--[[Translation missing --]]
--[[ L["Profiles"] = "Profiles"--]] 
--[[Translation missing --]]
--[[ L["Pull Aggro Bar Color"] = "Pull Aggro Bar Color"--]] 
--[[Translation missing --]]
--[[ L["Right"] = "Right"--]] 
--[[Translation missing --]]
--[[ L["Right-click|r to open the options menu"] = "Right-click|r to open the options menu"--]] 
--[[Translation missing --]]
--[[ L["ROGUE"] = "Rogue"--]] 
--[[Translation missing --]]
--[[ L["Scale"] = "Scale"--]] 
--[[Translation missing --]]
--[[ L["Sets how far inside the frame the threat bars will display from the 4 borders of the frame"] = "Sets how far inside the frame the threat bars will display from the 4 borders of the frame"--]] 
--[[Translation missing --]]
--[[ L["SFX"] = "SFX"--]] 
--[[Translation missing --]]
--[[ L["SHAMAN"] = "Shaman"--]] 
--[[Translation missing --]]
--[[ L["Short Numbers"] = "Short Numbers"--]] 
--[[Translation missing --]]
--[[ L["Show a bar for the amount of threat you will need to reach in order to pull aggro."] = "Show a bar for the amount of threat you will need to reach in order to pull aggro."--]] 
--[[Translation missing --]]
--[[ L["Show bars for these classes"] = "Show bars for these classes"--]] 
--[[Translation missing --]]
--[[ L["Show Classes..."] = "Show Classes..."--]] 
--[[Translation missing --]]
--[[ L["Show column headings"] = "Show column headings"--]] 
--[[Translation missing --]]
--[[ L["Show Headings"] = "Show Headings"--]] 
--[[Translation missing --]]
--[[ L["Show icon"] = "Show icon"--]] 
--[[Translation missing --]]
--[[ L["Show minimap button"] = "Show minimap button"--]] 
--[[Translation missing --]]
--[[ L["Show Omen"] = "Show Omen"--]] 
--[[Translation missing --]]
--[[ L["Show Omen when any of the following are true"] = "Show Omen when any of the following are true"--]] 
--[[Translation missing --]]
--[[ L["Show Omen when you are alone"] = "Show Omen when you are alone"--]] 
--[[Translation missing --]]
--[[ L["Show Omen when you are in a 5-man party"] = "Show Omen when you are in a 5-man party"--]] 
--[[Translation missing --]]
--[[ L["Show Omen when you are in a raid"] = "Show Omen when you are in a raid"--]] 
--[[Translation missing --]]
--[[ L["Show Omen when you have a pet out"] = "Show Omen when you have a pet out"--]] 
--[[Translation missing --]]
--[[ L["Show Omen when..."] = "Show Omen when..."--]] 
--[[Translation missing --]]
--[[ L["Show Pull Aggro Bar"] = "Show Pull Aggro Bar"--]] 
--[[Translation missing --]]
--[[ L["Show text"] = "Show text"--]] 
--[[Translation missing --]]
--[[ L["Show the Omen minimap button"] = "Show the Omen minimap button"--]] 
--[[Translation missing --]]
--[[ L["Show the Omen Title Bar"] = "Show the Omen Title Bar"--]] 
--[[Translation missing --]]
--[[ L["Show Threat %"] = "Show Threat %"--]] 
--[[Translation missing --]]
--[[ L["Show threat per second values"] = "Show threat per second values"--]] 
--[[Translation missing --]]
--[[ L["Show Threat Values"] = "Show Threat Values"--]] 
--[[Translation missing --]]
--[[ L["Show Title Bar"] = "Show Title Bar"--]] 
--[[Translation missing --]]
--[[ L["Show TPS"] = "Show TPS"--]] 
--[[Translation missing --]]
--[[ L["Show When..."] = "Show When..."--]] 
--[[Translation missing --]]
--[[ L["SHOW_CLASSES_DESC"] = "Show Omen threat bars for the following classes. The classes here refer to those people in your party/raid only with the exception of the 'Not In Party' option."--]] 
--[[Translation missing --]]
--[[ L["Slash Command"] = "Slash Command"--]] 
--[[Translation missing --]]
--[[ L["Smoothly animate bar changes"] = "Smoothly animate bar changes"--]] 
--[[Translation missing --]]
--[[ L["Sound Channel"] = "Sound Channel"--]] 
--[[Translation missing --]]
--[[ L["Sound to play"] = "Sound to play"--]] 
--[[Translation missing --]]
--[[ L["Spacing between each bar"] = "Spacing between each bar"--]] 
--[[Translation missing --]]
--[[ L["Switch the colors so that the bar background colors and the text colors are swapped."] = "Switch the colors so that the bar background colors and the text colors are swapped."--]] 
--[[Translation missing --]]
--[[ L["Tank Bar Color"] = "Tank Bar Color"--]] 
--[[Translation missing --]]
--[[ L["Tells Omen to additionally check your 'focus' and 'focustarget' before your 'target' and 'targettarget' in that order for threat display."] = "Tells Omen to additionally check your 'focus' and 'focustarget' before your 'target' and 'targettarget' in that order for threat display."--]] 
--[[Translation missing --]]
--[[ L["Tells Omen to enter Test Mode so that you can configure Omen's display much more easily."] = "Tells Omen to enter Test Mode so that you can configure Omen's display much more easily."--]] 
--[[Translation missing --]]
--[[ L["Temp Threat Bar Color"] = "Temp Threat Bar Color"--]] 
--[[Translation missing --]]
--[[ L["Test Mode"] = "Test Mode"--]] 
--[[Translation missing --]]
--[[ L["Test warnings"] = "Test warnings"--]] 
--[[Translation missing --]]
--[[ L["Texture to use for the frame's background"] = "Texture to use for the frame's background"--]] 
--[[Translation missing --]]
--[[ L["Texture to use for the frame's border"] = "Texture to use for the frame's border"--]] 
--[[Translation missing --]]
--[[ L["The background color for all threat bars"] = "The background color for all threat bars"--]] 
--[[Translation missing --]]
--[[ L["The background color for pets"] = "The background color for pets"--]] 
--[[Translation missing --]]
--[[ L["The background color for players under the effects of Fade, Mirror Image, Tricks of the Trade and Misdirection"] = "The background color for players under the effects of Fade, Mirror Image, Tricks of the Trade and Misdirection"--]] 
--[[Translation missing --]]
--[[ L["The background color for your Pull Aggro bar"] = "The background color for your Pull Aggro bar"--]] 
--[[Translation missing --]]
--[[ L["The background color for your tank's threat bar"] = "The background color for your tank's threat bar"--]] 
--[[Translation missing --]]
--[[ L["The background color for your threat bar"] = "The background color for your threat bar"--]] 
--[[Translation missing --]]
--[[ L["The color of the labels"] = "The color of the labels"--]] 
--[[Translation missing --]]
--[[ L["The color of the title text"] = "The color of the title text"--]] 
--[[Translation missing --]]
--[[ L["The font that the labels will use"] = "The font that the labels will use"--]] 
--[[Translation missing --]]
--[[ L["The font that the title text will use"] = "The font that the title text will use"--]] 
--[[Translation missing --]]
--[[ L["The outline that the labels will use"] = "The outline that the labels will use"--]] 
--[[Translation missing --]]
--[[ L["The outline that the title text will use"] = "The outline that the title text will use"--]] 
--[[Translation missing --]]
--[[ L["The size used to tile the background texture"] = "The size used to tile the background texture"--]] 
--[[Translation missing --]]
--[[ L["The texture that the bar will use"] = "The texture that the bar will use"--]] 
--[[Translation missing --]]
--[[ L["The thickness of the border"] = "The thickness of the border"--]] 
--[[Translation missing --]]
--[[ L["Thick Outline"] = "Thick Outline"--]] 
--[[Translation missing --]]
--[[ L["This section controls when Omen is automatically shown or hidden."] = "This section controls when Omen is automatically shown or hidden."--]] 
--[[Translation missing --]]
--[[ L["Threat"] = "Threat"--]] 
--[[Translation missing --]]
--[[ L["Threat [%]"] = "Threat [%]"--]] 
--[[Translation missing --]]
--[[ L["Tile Background"] = "Tile Background"--]] 
--[[Translation missing --]]
--[[ L["Tile the background texture"] = "Tile the background texture"--]] 
--[[Translation missing --]]
--[[ L["Title Bar Background Options"] = "Title Bar Background Options"--]] 
--[[Translation missing --]]
--[[ L["Title Bar Height"] = "Title Bar Height"--]] 
--[[Translation missing --]]
--[[ L["Title Bar Settings"] = "Title Bar Settings"--]] 
--[[Translation missing --]]
--[[ L["Title Text Options"] = "Title Text Options"--]] 
--[[Translation missing --]]
--[[ L["Toggle Focus"] = "Toggle Focus"--]] 
--[[Translation missing --]]
--[[ L["Toggle Omen"] = "Toggle Omen"--]] 
--[[Translation missing --]]
--[[ L["TPS"] = "TPS"--]] 
--[[Translation missing --]]
--[[ L["TPS Window"] = "TPS Window"--]] 
--[[Translation missing --]]
--[[ L["TPS_WINDOW_DESC"] = "The threat per second calculation is based on a real time sliding window of the last X seconds."--]] 
--[[Translation missing --]]
--[[ L["Turning this on will cause Omen to hide whenever you are in a battleground or arena."] = "Turning this on will cause Omen to hide whenever you are in a battleground or arena."--]] 
--[[Translation missing --]]
--[[ L["Turning this on will cause Omen to hide whenever you are in a city or inn."] = "Turning this on will cause Omen to hide whenever you are in a city or inn."--]] 
--[[Translation missing --]]
--[[ L["Turning this on will cause Omen to hide whenever you are not in combat."] = "Turning this on will cause Omen to hide whenever you are not in combat."--]] 
--[[Translation missing --]]
--[[ L["Use !ClassColors"] = "Use !ClassColors"--]] 
--[[Translation missing --]]
--[[ L["Use !ClassColors addon for class colors for the background color of threat bars"] = "Use !ClassColors addon for class colors for the background color of threat bars"--]] 
--[[Translation missing --]]
--[[ L["Use a different colored background for the tank's threat bar in Omen"] = "Use a different colored background for the tank's threat bar in Omen"--]] 
--[[Translation missing --]]
--[[ L["Use a different colored background for your threat bar in Omen"] = "Use a different colored background for your threat bar in Omen"--]] 
--[[Translation missing --]]
--[[ L["Use Auto Show/Hide"] = "Use Auto Show/Hide"--]] 
--[[Translation missing --]]
--[[ L["Use Class Colors"] = "Use Class Colors"--]] 
--[[Translation missing --]]
--[[ L["Use Focus Target"] = "Use Focus Target"--]] 
--[[Translation missing --]]
--[[ L["Use 'My Bar' color"] = "Use 'My Bar' color"--]] 
--[[Translation missing --]]
--[[ L["Use Same Background"] = "Use Same Background"--]] 
--[[Translation missing --]]
--[[ L["Use standard class colors for the background color of threat bars"] = "Use standard class colors for the background color of threat bars"--]] 
--[[Translation missing --]]
--[[ L["Use Tank Bar color"] = "Use Tank Bar color"--]] 
--[[Translation missing --]]
--[[ L["Use the same background settings for the title bar as the main window's background"] = "Use the same background settings for the title bar as the main window's background"--]] 
--[[Translation missing --]]
--[[ L["WARLOCK"] = "Warlock"--]] 
--[[Translation missing --]]
--[[ L["Warning Settings"] = "Warning Settings"--]] 
--[[Translation missing --]]
--[[ L["Warning Threshold %"] = "Warning Threshold %"--]] 
--[[Translation missing --]]
--[[ L["Warrior"] = "Warrior"--]] 
--[[Translation missing --]]
--[[ L["WARRIOR"] = "Warrior"--]] 
--[[Translation missing --]]
--[[ L["WARRIOR_FAQ"] = [=[The following data is obtained from |cffffd200http://www.tankspot.com/forums/f200/39775-wow-3-0-threat-values.html|r on 2nd Oct 2008 (credits to Satrina). The numbers are for a level 80.

|cffffd200Modifiers|r
Battle Stance ________ x 80
Berserker Stance _____ x 80
Tactical Mastery _____ x 121/142/163
Defensive Stance _____ x 207.35

Note that in our original threat estimations (that we use now in WoW 2.0), we equated 1 damage to 1 threat, and used 1.495 to represent the stance+defiance multiplier. We see that Blizzard's method is to use the multiplier without decimals, so in 2.x it would've been x149 (maybe x149.5); it is x207 (maybe 207.3) in 3.0. I expect that this is to allow the transport of integer values instead of decimal values across the Internet for efficiency. It appears that threat values are multiplied by 207.35 at the server, then rounded.

If you still want to use the 1 damage = 1 threat method, the stance modifiers are 0.8 and 2.0735, etc.

|cffffd200Threat Values  (stance modifiers apply unless otherwise noted):|r
Battle Shout _________ 78 (split)
Cleave _______________ damage + 225 (split)
Commanding Shout _____ 80 (split)
Concussion Blow ______ damage only
Damage Shield ________ damage only
Demoralising Shout ___ 63 (split)
Devastate ____________ damage + 5% of AP *** Needs re-checking for 8982 **
Dodge/Parry/Block_____ 1 (in defensive stance with Improved Defensive Stance only)
Heroic Strike ________ damage + 259
Heroic Throw _________ 1.50 x damage
Rage Gain ____________ 5 (stance modifier is not applied)
Rend _________________ damage only
Revenge ______________ damage + 121
Shield Bash __________ 36
Shield Slam __________ damage + 770
Shockwave ____________ damage only
Slam _________________ damage + 140
Spell Reflect ________ damage only (only for spells aimed at you)
Social Aggro _________ 0
Sunder Armour ________ 345 + 5%AP
Thunder Clap _________ 1.85 x damage
Vigilance ____________ 10% of target's generated threat (stance modifier is not applied)

You do not gain threat for reflecting spells targetted at allies with Improved Spell Reflect. When you reflect a spell for an ally, your ally gains the threat for the damage dealt by the reflected spell.
]=]--]] 
--[[Translation missing --]]
--[[ L["You are alone"] = "You are alone"--]] 
--[[Translation missing --]]
--[[ L["You are in a battleground"] = "You are in a battleground"--]] 
--[[Translation missing --]]
--[[ L["You are in a party"] = "You are in a party"--]] 
--[[Translation missing --]]
--[[ L["You are in a raid"] = "You are in a raid"--]] 
--[[Translation missing --]]
--[[ L["You are not in combat"] = "You are not in combat"--]] 
--[[Translation missing --]]
--[[ L["You are resting"] = "You are resting"--]] 
--[[Translation missing --]]
--[[ L["You have a pet"] = "You have a pet"--]] 

