-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/projects/omen-threat-meter/localization/

-- Korean localization by Sayclub.
local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("Omen", "koKR")
if not L then return end

L["*Not in Party*"] = "*파티에 속하지 않음*"
L["|cffff0000Error:|r Omen cannot use shake warning if you have turned on nameplates at least once since logging in."] = "|cffff0000오류:|r 만약 로그인 후 한번이라도 이름표를 표시했다면 Omen의 진동 경고를 사용 할 수 없습니다."
L["<Unknown>"] = "<무엇인가>"
L["> Pull Aggro <"] = "> 어그로 획득 <"
L["A collection of help pages"] = "도움말 페이지 목록"
L["Alpha"] = "투명도"
L["Always Show Self"] = "항상 자신 표시"
L["Always show your threat bar on Omen (ignores class filter settings), showing your bar on the last row if necessary"] = "Omen에 자신의 위협 수준 바를 항상 표시합니다 (직업 필터 설정 무시), 필요한 경우 마지막 줄에 자신의 바를 표시합니다"
L["Ambience"] = "환경 소리"
L["Animate Bars"] = "움직이는 바"
L["Attach to minimap"] = "미니맵에 붙이기"
L["AUTO_SHOW/HIDE_NOTE"] = "참고: 만약 수동으로 Omen 표시나 숨기기를 토글한다면, 지역을 이동하거나, 파티 또는 공격대에 참가 또는 떠나거나, 자동 표시/숨김 설정을 변경할 때까지 자동 표시/숨김 설정과 관계없이 계속 표시되거나 숨겨집니다."
L["Autocollapse"] = "자동 접기"
L["Autocollapse Options"] = "자동 접기 옵션"
L["Background Color"] = "배경 색상"
L["Background Options"] = "배경 옵션"
L["Background Texture"] = "배경 무늬"
L["Background Tile Size"] = "배경 배열 크기"
L["Bar BG Color"] = "바 배경 색상"
L["Bar Height"] = "바 높이"
L["Bar Inset"] = "바 삽입"
L["Bar Label Options"] = "바 제목 옵션"
L["Bar Settings"] = "바 설정"
L["Bar Spacing"] = "바 간격"
L["Bar Texture"] = "바 무늬"
L["Border Color"] = "테두리 색상"
L["Border Texture"] = "테두리 무늬"
L["Border Thickness"] = "테두리 두께"
L["Causes Omen to play a chosen sound effect"] = "선택한 소리 효과를 재생합니다"
L["Causes the entire game world to shake momentarily. This option only works if nameplates are turned off."] = "전체 게임 화면이 잠시 흔들립니다. 만약 이름표 표시가 켜져 있다면 이 옵션은 작동하지 않습니다."
L["Causes the entire screen to flash red momentarily"] = "화면 가장자리에 붉은색 깜박임 효과를 줍니다."
L["Center"] = "가운데"
L["Center Omen"] = "Omen 중앙으로"
L["Clamp To Screen"] = "화면에 고정"
L["Click Through"] = "클릭 무시"
L["Click|r to toggle the Omen window"] = "클릭|r Omen 창 토글"
L["Collapse to show a minimum number of bars"] = "최소한의 바를 표시하기 위해 접기를 합니다."
L["Configure"] = "설정"
L["Configure bar settings."] = "바를 설정합니다."
L["Configure title bar settings."] = "제목 바를 설정합니다."
L["Control the font size of the labels"] = "라벨의 글꼴 크기를 조절합니다."
L["Control the font size of the title text"] = "제목 문자의 글꼴 크기를 조절합니다"
L["Controls the frame strata of the main Omen window. Default: MEDIUM"] = "Omen 창의 프레임 우선순위를 조절합니다. 기본값: MEDIUM"
L["Controls the scaling of the main Omen window."] = "Omen 창의 크기를 조절합니다."
L["Controls the transparency of the main Omen window."] = "Omen 창의 투명도를 조절합니다."
L["Controls whether the main Omen window can be dragged offscreen"] = "Omen 창이 화면 밖으로 벗어나지 못하게 합니다"
L["DEATHKNIGHT"] = "죽음의 기사"
--[[Translation missing --]]
--[[ L["DEMONHUNTER"] = "Demon Hunter"--]] 
L["Disable while tanking"] = "방어 담당시 사용 안 함"
L["DISABLE_WHILE_TANKING_DESC"] = "방어 태세, 곰 변신, 정의의 격노나 혈기의 형상이 활성화 되어있을 때 모든 경고를 보이지 않습니다."
L["Display large numbers in Ks"] = "큰 숫자는 K로 표시합니다."
L["DRUID"] = "드루이드"
L["Enable Screen Flash"] = "화면 깜박임 사용"
L["Enable Screen Shake"] = "화면 진동 사용"
L["Enable Sound"] = "소리 사용"
L["Enable Warning Message"] = "경고 메시지 사용"
L["FAQ Part 1"] = "FAQ Part 1"
L["FAQ Part 2"] = "FAQ Part 2"
L["Font"] = "글꼴"
L["Font Color"] = "글꼴 색상"
L["Font Outline"] = "글꼴 외곽선"
L["Font Size"] = "글꼴 크기"
L["Frame Strata"] = "프레임 우선순위"
L["Frame's background color"] = "창의 배경 색상을 설정합니다"
L["Frame's border color"] = "창의 테두리 색상을 설정합니다"
L["Frequently Asked Questions"] = "자주 묻는 질문"
L["FuBar Options"] = "FuBar 옵션"
L["General Settings"] = "일반 설정"
L["GENERAL_FAQ"] = [=[
|cffffd200Omen2와 Omen3가 어떻게 다른가요?|r

Omen3는 블리자드 위협 수준 API와 위협 수준 이벤트에 전적으로 의지합니다. Omen2와 다르게 계산을 시도하거나 위협 수준을 추측하지 않습니다.

Omen2는 Threat-2.0 라이브러리를 사용합니다. 이 라이브러리는 각 개별 위협 수준에 대해 전투 로그, 주문 시전, 버프, 디버프, 태세, 특성과 장비의 변화를 모니터링 합니다. 위협 수준은 알고 있거나 관찰된 행동으로부터 예상해서 계산되었습니다. 밀쳐내기 같은 많은 기술들은 단지 추측으로만(위협 수준이 50% 감소되었다고) 판단해서 거의 신뢰할 수 없었습니다.

또한 Threat-2.0 라이브러리는 애드온 커뮤니케이션을 포함하고 있어서 Threat-2.0을 사용하는 다른 공격대원에게 당신의 위협 수준을 전송했습니다. 이 데이터는 나중에 공격대 전체의 위협 수준 정보를 표시하는데 사용되었습니다.

3.0.2 패치부터, Omen은 더이상 이러한 작업을 하지 않게 되어 위협 수준 라이브러리가 더이상 필요하지 않게 되었습니다. Omen3는 모든 위협 수준의 정확한 수치를 포함하는 블리자드의 새로운 내장 위협 수준 모니터를 사용합니다. Omen3는 네트워크 트래픽, CPU와 메모리 사용량을 증가시키던 데이터의 동기화나, 전투 로그 분석 또는 추측이 필요하지 않습니다. 특정 위협 수준 이벤트(파멸의 어둠의 착지 시 위협 수준 초기화같은)를 위한 우두머리 모듈의 실행도 더이상 필요하지 않습니다.

이 새로운 구현의 또 다른 장점은 몹에 대한 NPC의 위협 수준(예, 인간형 칼렉고스)을 포함한다는 것입니다. 하지만, 약간의 단점이 있습니다; 갱신의 주기가 더 느리고, 파티/공격대원이 몹을 대상 지정하지 않고 있거나 자신이 직접 전투 중이지 않을 때는 위협 수준 세부 정보를 얻을 수 없습니다.

|cffffd2002개의 회색 세로줄을 어떻게 없애나요?|r

Omen을 잠그세요. Omen을 잠그면 창의 이동이나 크기 변경을 방지하며, 열의 크기 변경도 방지합니다. 잠그지 않았다면, 2개의 회색 줄은 열의 크기를 조절하는 손잡이입니다.

|cffffd200어떻게 Omen3를 Omen2처럼 보이게 하나요?|r

배경 무늬와 테두리 무늬를 블리자드 툴팁으로 변경하고, 배경 색상을 검은색으로 변경하고(밝기 바를 맨 밑으로 드래그하세요), 테두리 색상을 파란색으로 변경하세요.

|cffffd200왜 전투 중인 몹을 대상 지정했을 때 아무런 위협 수준이 표시가 안되나요?|r

블리자드 위협 수준 API는 당신이 직접 전투에 참여하고 있지 않은 몹의 위협 수준 데이터를 제공하지 않습니다. 우리는 네트워크 트래픽을 줄이기 위한 블리자드의 노력이라고 생각합니다.

|cffffd200이 블리자드의 제한을 해결할 수 없나요? 공격하기 전까진 내 소환수의 위협 수준을 알 수가 없습니다.|r

단도직입적으로 이 제한을 해결할 수 있는 방법이 없습니다 (정확히 Omen2가 했던 방법입니다).

Omen3의 목표는 정확한 위협 수준 데이터를 제공하는 것입니다, 당신의 FPS를 낮추는 과정과 추측을 하지 않을 겁니다. 소환수/탱커를 믿고, 2초만 기다린 후 공격하고 첫 위협 수준을 읽기 위해 얼음창같은 낮은 피해 주문을 사용하세요.]=]
L["GENERAL_FAQ2"] = [=[|cffffd200광역 모드를 되돌릴 수 있나요?|r

다시 말하자면, 이것은 위협 수준 수치를 추측하지 않고선 불가능합니다. 블리자드의 위협 수준 API는 오직 공격대의 누군가에게 대상 지정된 유닛에게만 위협 수준 데이터를 요청할 수 있습니다. 이것은 만약 20마리의 몹이 있고 공격대에 의해 6마리만 대상 지정되었을 때, 나머지 14마리 몹에 대한 정확한 위협 수준 데이터는 얻을 수 없다는 걸 의미합니다.

또한 이것은 치유와 버프에 따른 부분을 추측하기에 굉장히 복잡합니다 (당신이 전투 중인 몹의 숫자에 따라 나누어서 위협 수준을 얻습니다) 왜냐하면 군중 제어 효과를 받은 몹은 (양 변이, 추방, 혼절시키기, 등등) 위협 수준 테이블이 변하지 않고 애드온은 몇 마리의 몹이 당신과 전투 중인지 확실하게 알려줄 수 없습니다. Omen2의 추측은 거의 대부분 틀렸었습니다.

|cffffd200Omen3가 알려준 위협 수준 %와 마우스오버 유닛의 툴팁에 표시된 위협 수준 %가 다릅니다. 왜인가요?|r

블리자드의 위협 수준 백분율은 0% 에서 100% 사이에 분포합니다, 따라서 당신은 항상 100%에서 어그로를 획득합니다. Omen은 원래의 변형되지 않은 수치로 근접일 땐 110%에서 근접이 아닐 땐 130%에서 어그로를 획득하는 것으로 보고합니다.

보편적 합의점으로, 몹의 현재 대상을 방어 전담으로 생각하고 100%의 위협 수준을 가진 것으로 정의합니다.

|cffffd200Omen3가 동기화나 전투 로그 분석을 하나요?|r

아니오. Omen3는 동기화나 전투 로그 분석을 시도하지 않습니다. 현재로선 그렇게 할 의도가 없습니다.

|cffffd200위협 수준 갱신이 느려요...|r

블리자드가 우리에게 위협 수준 수치를 갱신할 때마다 Omen3도 위협 수준 수치를 갱신합니다.

사실, 블리자드는 1초 마다 갱신해줍니다, 이것은 Omen2가 사용하던 동기화 갱신보다 빠릅니다. Omen2에선, 다른 공격대원들에게 3초 마다 당신의 위협 수준 수치를 전송했습니다(방어 전담일 땐 1.5초).

|cffffd200제안이나 버그 보고를 어디서 할 수 있나요?|r

http://forums.wowace.com/showthread.php?t=14249

|cffffd200Omen3를 누가 제작했나요?|r

Xinhuan (Blackrock/Barthilas US 얼라이언스) 가 했습니다.

|cffffd200Paypal 기부를 받나요?|r

네, xinhuan AT gmail DOT com으로 보내주세요.]=]
L["Grow bars upwards"] = "바 위로 확장"
L["Heading background color"] = "제목 배경 색상을 설정합니다"
L["Heading BG Color"] = "제목 배경 색상"
L["Height of each bar"] = "각 바의 높이를 설정합니다"
L["Height of the title bar. The minimum height allowed is twice the background border thickness."] = "제목 바의 높이를 설정합니다. 최소 높이는 배경 테두리 두께의 2배입니다."
L["Help File"] = "도움말"
L["Hide minimap/FuBar icon"] = "미니맵/FuBar 아이콘 숨기기"
L["Hide Omen"] = "Omen 숨기기"
L["Hide Omen entirely if it collapses to show 0 bars"] = "바의 갯수가 0개일 때 Omen을 숨깁니다"
L["Hide Omen on 0 bars"] = "바가 0개일 때 Omen 숨기기"
L["However, hide Omen if any of the following are true (higher priority than the above)."] = "다음 중 하나라도 만족하면 Omen을 숨깁니다 (위의 설정보다 우선 순위입니다)."
L["HUNTER"] = "사냥꾼"
L["Ignore Player Pets"] = "플레이어 소환수들 무시"
L["IGNORE_PLAYER_PETS_DESC"] = [=[
위협 수준 데이터를 표시할 유닛을 정할 때 Omen이 적대적 플레이어의 소환수는 걸러내도록 지시합니다.

플레이어의 소환수가 |cffffff78적극적|r 또는 |cffffff78방어적|r 모드일 때는 위협 수준 테이블을 유지하고 가장 높은 위협 수준으로 대상을 공격하는 일반적인 몹처럼 작동합니다. 만약 소환수가 특정 대상을 공격하도록 지시하면, 소환수는 여전히 위협 수준 테이블을 유지하지만 지정한 대상에게 100%의 위협 수준을 가진것으로 고정됩니다. 플레이어의 소환수는 당신을 공격하도록 강제로 도발할 수 있습니다.

하지만, |cffffff78수동적|r 모드의 플레이어 소환수는 위협 수준 테이블을 가지지 않으며, 그들을 도발할 수 없습니다. 소환수는 어떠한 위협 수준 테이블을 가지지 않은 채로 오직 공격하도록 지시된 대상을 공격합니다.

플레이어 소환수를 |cffffff78따르기|r로 지시했을 때, 소환수의 위협 수준 테이블은 즉시 삭제되며 공격을 멈춥니다, 하지만 적극적/방어적 모드에 따라서 즉시 새로운 대상을 다시 얻습니다.]=]
L["Invert Bar/Text Colors"] = "바/문자 색상 반대로"
L["Left"] = "왼쪽"
L["Lock Omen"] = "Omen 잠그기"
L["Locks Omen in place and prevents it from being dragged or resized."] = "Omen의 위치나 크기를 조절하지 못하도록 잠급니다."
L["MAGE"] = "마법사"
L["Makes the Omen window non-interactive"] = "Omen 창 상호작용 비활성"
L["Master"] = "주 음량"
L["Max bars to show"] = "표시할 최대 바"
L["Max number of bars to show"] = "표시할 바의 최대 갯수"
L["Music"] = "배경음악"
L["'My Bar' BG Color"] = "'플레이어 바'의 배경 색상"
L["Name"] = "이름"
L["None"] = "없음"
L["Omen Quick Menu"] = "Omen 빠른 메뉴"
L["OMEN_DESC"] = "Omen은 당신이 전투 중인 몹들의 위협 수준을 보여주는 가벼운 위협 수준 미터기입니다. Omen의 외형과 작동법을 변경할 수 있으며, 모든 캐릭터에 다른 프로필을 설정할 수 있습니다."
L["OMEN_SLASH_DESC"] = "이 버튼들은 슬래시 명령 /omen 에 있는 것과 같은 기능을 실행합니다."
L["OMEN_WARNINGS_DESC"] = "당신이 어그로를 획득하면 언제 어떻게 Omen이 경고할 지 설정합니다."
L["Open Config"] = "설정 열기"
L["Open Omen's configuration panel"] = "Omen의 설정 창을 엽니다"
L["Open the configuration dialog"] = "설정 창을 엽니다"
L["Outline"] = "얇은 외곽선"
L["PALADIN"] = "성기사"
L["Passed %s%% of %s's threat!"] = "%2$s 위협 수준의 %1$s%% 초과함!"
L["PET"] = "소환수"
L["Pet Bar Color"] = "소환수 바 색상"
L["Position"] = "위치"
L["PRIEST"] = "사제"
L["Print a message to screen when you accumulate too much threat"] = "당신이 너무 많은 위협 수준을 모으면 화면에 메시지를 보여줍니다."
L["Profiles"] = "프로필"
L["Pull Aggro Bar Color"] = "어그로 획득 바 색상"
L["Right"] = "오른쪽"
L["Right-click|r to open the options menu"] = "우-클릭|r 옵션 메뉴 열기"
L["ROGUE"] = "도적"
L["Scale"] = "크기"
L["Sets how far inside the frame the threat bars will display from the 4 borders of the frame"] = "프레임의 4 모서리와 위협 수준 바 사이의 거리를 설정합니다"
L["SFX"] = "효과음"
L["SHAMAN"] = "주술사"
L["Short Numbers"] = "숫자 축약"
L["Show a bar for the amount of threat you will need to reach in order to pull aggro."] = "어그로를 획득하기 위해 당신이 도달해야 할 위협 수준 바를 표시합니다."
L["Show bars for these classes"] = "이 직업들의 바를 표시합니다"
L["Show Classes..."] = "직업 표시..."
L["Show column headings"] = "열 제목 표시"
L["Show Headings"] = "제목 표시"
L["Show icon"] = "아이콘 표시"
L["Show minimap button"] = "미니맵 버튼 표시"
L["Show Omen"] = "Omen 표시"
L["Show Omen when any of the following are true"] = "다음 중 하나라도 만족하면 Omen을 표시합니다"
L["Show Omen when you are alone"] = "솔로잉일 경우에 Omen을 표시합니다"
L["Show Omen when you are in a 5-man party"] = "5인 파티일 경우에 Omen을 표시합니다"
L["Show Omen when you are in a raid"] = "공격대일 경우에 Omen을 표시합니다"
L["Show Omen when you have a pet out"] = "소환수를 가진 경우에 Omen을 표시합니다"
L["Show Omen when..."] = "Omen 표시 조건..."
L["Show Pull Aggro Bar"] = "어그로 획득 바 표시"
L["Show text"] = "문자 표시"
L["Show the Omen minimap button"] = "Omen 미니맵 버튼을 표시합니다"
L["Show the Omen Title Bar"] = "Omen 제목 바를 표시합니다"
L["Show Threat %"] = "위협 수준 % 표시"
L["Show threat per second values"] = "초당 위협 수준 값을 표시합니다"
L["Show Threat Values"] = "위협 수준 수치 표시"
L["Show Title Bar"] = "제목 바 표시"
L["Show TPS"] = "TPS 표시"
L["Show When..."] = "표시 조건..."
L["SHOW_CLASSES_DESC"] = "다음 직업들을 위한 Omen 위협 수준 바를 표시합니다. 여기 직업은 '파티에 속하지 않음' 옵션을 제외하고 당신의 파티/공격대에 속한 사람들만 표시합니다."
L["Slash Command"] = "슬래시 명령어"
L["Smoothly animate bar changes"] = "바가 부드럽게 움직이도록 변경합니다"
L["Sound Channel"] = "사운드 채널"
L["Sound to play"] = "재생할 소리"
L["Spacing between each bar"] = "각 바 사이의 간격을 설정합니다"
L["Switch the colors so that the bar background colors and the text colors are swapped."] = "바 배경 색상과 문자 색상이 교환되도록 색상을 전환합니다."
L["Tank Bar Color"] = "방어 전담 바 색상"
L["Tells Omen to additionally check your 'focus' and 'focustarget' before your 'target' and 'targettarget' in that order for threat display."] = "Omen에 당신의 '대상'과 '대상의 대상'에 대한 위협 수준을 표시하기 전에 추가로 당신의 '주시 대상'과 '주시 대상의 대상'을 검사합니다."
L["Tells Omen to enter Test Mode so that you can configure Omen's display much more easily."] = "Omen을 쉽게 설정할 수 있도록 테스트 모드에 들어갑니다."
L["Temp Threat Bar Color"] = "일시적 위협 수준 바 색상"
L["Test Mode"] = "테스트 모드"
L["Test warnings"] = "테스트 경고"
L["Texture to use for the frame's background"] = "창의 배경에 사용할 무늬를 설정합니다"
L["Texture to use for the frame's border"] = "창의 테두리에 사용할 무늬를 설정합니다"
L["The background color for all threat bars"] = "모든 위협 수준 바에 대한 배경 색상을 지정합니다"
L["The background color for pets"] = "소환수에 대한 배경 색상을 지정합니다"
L["The background color for players under the effects of Fade, Mirror Image, Tricks of the Trade and Misdirection"] = "소실, 환영 복제, 구원의 손길(문양), 속임수 거래와 눈속임 효과를 가진 플레이어의 배경 색상을 설정합니다"
L["The background color for your Pull Aggro bar"] = "당신의 어그로 획득 바에 대한 배경 색상을 지정합니다"
L["The background color for your tank's threat bar"] = "당신의 방어 전담(탱커) 위협 수준 바에 대한 배경 색상을 지정합니다"
L["The background color for your threat bar"] = "플레이어(당신)의 바에 대한 배경 색상을 지정합니다"
L["The color of the labels"] = "라벨의 색상을 설정합니다"
L["The color of the title text"] = "제목 문자의 색상을 설정합니다"
L["The font that the labels will use"] = "라벨에 사용할 글꼴을 설정합니다"
L["The font that the title text will use"] = "제목 문자에 사용할 글꼴을 설정합니다"
L["The outline that the labels will use"] = "라벨에 사용할 외곽선을 설정합니다"
L["The outline that the title text will use"] = "제목 문자에 사용할 외곽선을 설정합니다"
L["The size used to tile the background texture"] = "배경 무늬를 배열할 크기를 설정합니다"
L["The texture that the bar will use"] = "바에 사용할 무늬를 설정합니다"
L["The thickness of the border"] = "테두리의 두께를 설정합니다"
L["Thick Outline"] = "두꺼운 외곽선"
L["This section controls when Omen is automatically shown or hidden."] = "Omen이 자동으로 표시되거나 숨겨질 조건을 설정합니다."
L["Threat"] = "위협 수준"
L["Threat [%]"] = "위협 수준 [%]"
L["Tile Background"] = "배경 바둑판 배열"
L["Tile the background texture"] = "배경 무늬를 바둑판 배열합니다"
L["Title Bar Background Options"] = "제목 바 배경 옵션"
L["Title Bar Height"] = "제목 바 높이"
L["Title Bar Settings"] = "제목 바 설정"
L["Title Text Options"] = "제목 문자 옵션"
L["Toggle Focus"] = "주시 대상 켜기/끄기"
L["Toggle Omen"] = "Omen 열기/닫기"
L["TPS"] = "TPS"
L["TPS Window"] = "TPS 창"
L["TPS_WINDOW_DESC"] = "초당 위협 수준 계산을 X 초 마다 실시간으로 창에 표시합니다."
L["Turning this on will cause Omen to hide whenever you are in a battleground or arena."] = "당신이 전장이나 투기장에 있을 때 Omen을 숨깁니다."
L["Turning this on will cause Omen to hide whenever you are in a city or inn."] = "당신이 대도시나 여관에 있을 때 Omen을 숨깁니다."
L["Turning this on will cause Omen to hide whenever you are not in combat."] = "당신이 전투 중이 아닐 때 Omen을 숨깁니다."
L["Use !ClassColors"] = "!ClassColors 사용"
L["Use !ClassColors addon for class colors for the background color of threat bars"] = "위협 수준 바의 배경 색상에 직업 색상 표시를 위해 !ClassColors 애드온을 사용합니다"
L["Use a different colored background for the tank's threat bar in Omen"] = "Omen에서 방어 전담(탱커)의 위협 수준 바에 다른 색상을 사용합니다"
L["Use a different colored background for your threat bar in Omen"] = "Omen에서 플레이어(당신)의 위협 수준 바에 다른 색상을 사용합니다"
L["Use Auto Show/Hide"] = "자동 표시/숨김 사용"
L["Use Class Colors"] = "직업 색상 사용"
L["Use Focus Target"] = "주시 대상 사용"
L["Use 'My Bar' color"] = "'플레이어 바'에 색상 사용"
L["Use Same Background"] = "같은 배경 사용"
L["Use standard class colors for the background color of threat bars"] = "위협 수준 바의 배경 색상에 기본 직업 색상을 사용합니다"
L["Use Tank Bar color"] = "방어 전담 바 색상 사용"
L["Use the same background settings for the title bar as the main window's background"] = "제목 바에 메인 창의 배경과 같은 배경 설정을 사용합니다"
L["WARLOCK"] = "흑마법사"
L["Warning Settings"] = "경고 설정"
L["Warning Threshold %"] = "% 값에 경고"
L["Warrior"] = "전사"
L["WARRIOR"] = "전사"
L["WARRIOR_FAQ"] = [=[The following data is obtained from |cffffd200http://www.tankspot.com/forums/f200/39775-wow-3-0-threat-values.html|r on 2nd Oct 2008 (credits to Satrina). The numbers are for a level 80.

|cffffd200Modifiers|r
Battle Stance ________ x 80
Berserker Stance _____ x 80
Tactical Mastery _____ x 121/142/163
Defensive Stance _____ x 207.35

Note that in our original threat estimations (that we use now in WoW 2.0), we equated 1 damage to 1 threat, and used 1.495 to represent the stance+defiance multiplier. We see that Blizzard's method is to use the multiplier without decimals, so in 2.x it would've been x149 (maybe x149.5); it is x207 (maybe 207.3) in 3.0. I expect that this is to allow the transport of integer values instead of decimal values across the Internet for efficiency. It appears that threat values are multiplied by 207.35 at the server, then rounded.

If you still want to use the 1 damage = 1 threat method, the stance modifiers are 0.8 and 2.0735, etc.

|cffffd200Threat Values  (stance modifiers apply unless otherwise noted):|r
Battle Shout _________ 78 (split)
Cleave _______________ damage + 225 (split)
Commanding Shout _____ 80 (split)
Concussion Blow ______ damage only
Damage Shield ________ damage only
Demoralising Shout ___ 63 (split)
Devastate ____________ damage + 5% of AP *** Needs re-checking for 8982 **
Dodge/Parry/Block_____ 1 (in defensive stance with Improved Defensive Stance only)
Heroic Strike ________ damage + 259
Heroic Throw _________ 1.50 x damage
Rage Gain ____________ 5 (stance modifier is not applied)
Rend _________________ damage only
Revenge ______________ damage + 121
Shield Bash __________ 36
Shield Slam __________ damage + 770
Shockwave ____________ damage only
Slam _________________ damage + 140
Spell Reflect ________ damage only (only for spells aimed at you)
Social Aggro _________ 0
Sunder Armour ________ 345 + 5%AP
Thunder Clap _________ 1.85 x damage
Vigilance ____________ 10% of target's generated threat (stance modifier is not applied)

You do not gain threat for reflecting spells targetted at allies with Improved Spell Reflect. When you reflect a spell for an ally, your ally gains the threat for the damage dealt by the reflected spell.
]=]
L["You are alone"] = "솔로잉시"
L["You are in a battleground"] = "전장 참여"
L["You are in a party"] = "파티 참여"
L["You are in a raid"] = "공격대 참여"
L["You are not in combat"] = "비 전투 시"
L["You are resting"] = "휴식 상태 시"
L["You have a pet"] = "소환수를 가졌을 때"

