-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/projects/routes/localization/

local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("Routes", "ruRU")
if not L then return end

L[" Data"] = "Данные"
L[" Gatherer/HandyNotes currently does not support callbacks, so this is impossible for Gatherer/HandyNotes."] = "Gatherer/HandyNotes в данный момент не поддерживают обратные вызовы, т.о. это не возможно для Gatherer/HandyNotes."
L["%s - Node %d"] = "%s - Узел %d"
L["|cffffd200     %d|r node(s) are at |cffffd2000|r yards of a cluster point"] = "|cffffd200     %d|r точек сбора находятся в |cffffd2000|r метрах от указанного места"
L["|cffffd200     %d|r node(s) are between |cffffd200%d|r-|cffffd200%d|r yards of a cluster point"] = "|cffffd200     %d|r точек находятся между |cffffd200%d|r и |cffffd200%d|r метрами от указанного места"
L["A route with that name already exists. Overwrite?"] = "Маршрут с таким именем уже существует. Перезаписать?"
L["A taboo with that name already exists. Overwrite?"] = "Запрещенная зона с таким именем уже существует. Перезаписать?"
L["Add"] = "Добавить"
L["Add node after (green)"] = "Добавить узел после (зеленый)"
L["Add node before (red)"] = "Добавить узел до (красный)"
L["Always show"] = "Всегда показывать"
L["An updated copy of TomTom is required for TomTom integration to work"] = "Для работы интеграции с TomTom требуется обновленная версия TomTom"
L["Archaeology"] = "Археология"
L["Are you sure you want to delete this route?"] = "Вы уверены, что хотите удалить этот маршрут?"
L["Are you sure you want to delete this taboo? This action will also remove the taboo from all routes that use it."] = "Вы уверены, что хотите удалить запретную зону? Это действие также удалит её из всех маршрутов."
L["Are you sure you want to recreate this route? This will delete all customized settings for this route."] = "Вы уверены, что хотите пересоздать этот маршрут? Это удалит все персональные настройки для этого маршрута."
L["Auto show and hide routes based on your professions"] = "Автоматическое сокрытие маршрутов на основе проффесии"
L["Auto show/hide"] = "Автоматическое сокрытие"
L["Auto Show/Hide per route type"] = "Автоматическое скрытие по типу маршрута"
L["Auto Show/Hide settings"] = "Настройки автоматического скрытия"
L["Automatic route updating"] = "Автоматическое обновление маршрута"
L["AUTOMATIC_UPDATE_TEXT"] = [=[Routes автоматически обновляет Ваши маршруты и добавляет/удаляет узлы, когда это требуется, если Вы используете |cffffff78GatherMate|r или |cffffff78Cartographer_<Profs>|r как источники данных. |cffffff78Gatherer/HandyNotes|r не поддерживаются т.к. в данный момент они не поддерживают обратные вызовы.


Когда Вы находите новый узел в любом из этих дополнений, Routes просматривает зону в поисках существующих маршрутов соответствующего типа и вставляет узел в лучьшее место маршрута. Таким же образом, когда Вы удаляете узел в этих дополнениях, Routes также удаляет узел из соответствующего маршрута.

Движение существующего положения узлов на несколько ярдов отрабатывается как удаление узла с последующей его вставкой. Фактически это делается также как и в дополнениях GatherMate и Cartographer_<Profs>.

Для остановки такого автоматического поведения, Вы можете выключить это в настройках следуя следующим шагам:

|cffffff781.|r  Найдите |cffffff78Routes|r в корне дерева слева экрана настроек.

|cffffff782.|r Снимите галочки рядом с соответствующими источниками данных.
]=]
L["Background"] = "В фоне"
L["Background Disclaimer"] = "Это заставляет выполнять создание маршрута в фоне, но несколько медленее чем при блокировании ВоВ. Пожалуйста отметьте себе то, что это заметно снижает производительность ВоВ."
L["Cancel route edit"] = "Отменить редактирование маршрута"
L["Cancel taboo edit"] = "Отменить редактирование запретной зоны"
L["Cartographer_Waypoints module is missing or disabled"] = "Модуль Cartographer_Waypoints отсутствует или отключен"
L["Change default hidden route color"] = "Изменить цвет по умолчанию скрытых маршрутов"
L["Change default route color"] = "Изменить цвет по умолчанию маршрутов"
L["Change direction (TomTom)"] = "Изменить направление (TomTom)"
L["Change the line color"] = "Изменить цвет линии"
-- L["Cluster"] = "Cluster"
-- L["Cluster Radius"] = "Cluster Radius"
-- L["Cluster this route"] = "Cluster this route"
-- L["CLUSTER_DESC"] = "Clustering a route makes Routes take all the nodes that are near each other and combine then into a single node as a travel point. This process takes a while, but is reasonably fast."
-- L["CLUSTER_RADIUS_DESC"] = "The maximum distance a node will be away from its cluster node point. The default is 60 yards because the detection radius of tracking skills is 80 yards."
L["Color of lines"] = "Цвета линий"
-- L["Create Bare Route"] = "Create Bare Route"
L["Create Route"] = "Создать маршрут"
L["Create Route from Data Sources"] = "Создать маршрут из источников данных"
L["Create Taboo"] = "Создать запрещенную зону"
L["CREATE_BARE_ROUTE_DESC"] = "Это создаст маршрут только с 3 начальными точками в нем, и не будет использовать никаких данных из любых источников. Вы должны будите вручную редактировать маршрут для добавления и удаления узлов."
L["CREATE_ROUTE_TEXT"] = [=[Создание маршрута проходит в 4 простых шага. Первое, найдите |cffffff78Add|r секцию слева.

|cffffff781.|r Введите имя маршрута и нажмите |cffffff78ENTER|r или щелкните по кнопке |cffffff78OK|r.

|cffffff782.|r Выберите локацию для создания в ней маршрута.

|cffffff783.|r Выберите источники данных.

|cffffff784.|r Выберите тип данных использующихся в Вашем маршруте.


|cffffd200Примечания:|r

*Важно нажать  |cffffff78ENTER|r или щелкнуть кнопку |cffffff78OK|r при вводе названия маршрута, иначе он не будет сохранен.

* Если маршрут успешно создан, Вы увидите розовые линии покрывающие выбранную локацию на карте мира. Запись для каждого будет создана слева под надписью Маршруты. Начальный маршрут не оптимизирован и нуждается в оптимизации.
]=]
L["CREATE_TABOOS_TEXT"] = [=[|cffffff78Запрещенные области|r представляют собой области (2D многоугольники) на карте мира, которые позволяют легко дать понять Routes, что они должны быть проигнорированы. Когда такие области определены, Routes активно игнорирует любые узлы в этих областях, и придпринимает дополнительные усилия, чтобы созданные пути не пересекали эти области. Это широко используется для потметки таких мест, через которые нежелательно ходить, а именно парящие острова, пещеры, высокие горы, вражеские города итд.

Запрещенные области создаются при помощи следующих шагов:

|cffffff781.|r Найдите |cffffff78Taboos|r в корне меню на левом экране настроек.

|cffffff782.|r  Введите имя запрещенной области и нажмите |cffffff78ENTER|r или щелкните по кнопке |cffffff78OK|r.

|cffffff783.|r Выберите имя локации в выпадающем списке для создания в ней запрещенной зоны.

|cffffff784.|r Щелкните по |cffffff78Create Taboo|r.

|cffffff785.|r Найдите созданную зону на левой панели настроек в меню |cffffff78Taboos|r.

|cffffff786.|r Щелкните по кнопке |cffffff78Edit taboo region|.

|cffffff787.|r Откройте карту мира и выберите, если необходимо, нужную локацию для запрещенной зоны.

|cffffff788.|r  Вы сможете увидеть треугольную затененную область на карте мира. Отредактируйте запрещенную зону путем
a) |cffffff78Претаскивания|r узлов многоугольника;
b) Добавления узла в многоугольник щелчком  |cffffff78ЛКМ|r между узлами;
c) Удаления узла из многоугольника щелчком |cffffff78ПКМ|r по существующему узлу.

|cffffff789.|r  Щелкните по кнопке |cffffff78Save taboo edit|r чтобы сохранить изменения, или по кнопке |cffffff78Cancel taboo edit|r чтобы не сохранять их.

Запрещенные области могут накладываться друг на друга, пересекаться между собой и содержать любое количество узлов по Вашему желанию. Это значит что Вы можете создавать очень сложные и точные запрещенные области если захотите этого.

 
|cffffd200Примечания:|r

*Однажды созданную запрещенную зону Вы можете прекрепить к существущему маршруту в его настройках. Вы должны заново оптимизировать маршрут после прекрепления или удаления запрещенной зоны из маршрута.

*Редактирование запрещенной зоны будет влиять на все маршруты её использующие, также удаление запрещенной зоны удалит её из всех маршрутов её использующих.
]=]
L["Creating a route"] = "Создание маршрута"
L["Creating a taboo region"] = "Создание запрещенной области"
-- L["Customizing route display"] = "Customizing route display"
L["CUSTOMIZING_ROUTE_TEXT"] = [=[Вы можете легко настроить отображение Ваших маршрутов на карте.  Настройки состоят из двух частей. Раздела |cffffff78Options|r слева, содержащего глобальные настройки применяемые к всему,  и настроек |cffffff78Line Settings|r для каждого отдельного маршрута, используемых для изменения настроек, отличных от глобальных настроек.

Для прорисовки карты, Вы уможете указать на каких картах Routes должен отрисовывать Ваши маршруты, также как и их цвет и толщину линий. Дополнительно Вы можете указать должны ли линии на миникарте отображаться пунктиром, накладываться на стрелку слежения и иконки узлов расставленные  |cffffff78GatherMate|r/|cffffff78Cartographer|r/|cffffff78Gatherer|r/|cffffff78HandyNotes|r.

Каждому маршруту с помощью настроек может быть назначен уникальный цвет и толщина линии, он также может быть полностью скрыт. Это позволяет Вам отмечать маршруты , которые Вы больше не хотите использовать, но не хотите удалять из отображения на картах. Настройка |cffffff78Show hidden routes|r в глобальных настройках может быть использована для прекрытия индивидуальной настройки маршрута.

Также Вы можете выбрать |cffffff78Auto show/hide|r  маршруты на основе типа узлов, которые они содержат, такие как узлы горного дела или травничества, а также выбрать отображение маршрута только если Вы владеете данными проффесиями, а также отображение маршрута только при включении данной способности, также всегда отображать маршруты, или никогда их не отображать. Если маршрут


]=]
L["Default route"] = "Маршрут по умолчанию"
L["Delete"] = "Удалить"
L["Delete node"] = "Удалить узел"
L["Delete Taboo"] = "Удалить запрет"
L["Delete this taboo region permanently. This will also remove it from all routes that use it."] = "Навсегда удалить запрещенную область. Это также удалит её из всех маршрутов."
L["Direction changed"] = "Направление изменено"
-- L["Do not draw gaps for clustered node points in routes."] = "Do not draw gaps for clustered node points in routes."
-- L["Draw line gaps"] = "Draw line gaps"
L["Draw on minimap when indoors"] = "Отображать на миникарте, при нахождении внутри зданий"
L["Edit route"] = "Редактировать маршрут"
L["Edit Route Manually"] = "Редактировать маршрут вручную"
L["Edit taboo region"] = "Редактировать запрещенную зону"
L["Edit this route on the world map"] = "Редактировать маршрут на карте мира"
L["Edit this taboo region on the world map"] = "Редактировать запрещенную зону на карте мира"
L["Extra optimization"] = "Экстра оптимизация"
L["ExtractGas"] = "Газ"
L["ExtraOptDesc"] = "Включение этой опции делает оптимизацию ~40% длительнее, но соданные маршруты становятся немного лучьше. Рекомендуется выключить."
L["FAQ"] = "ЧаВо"
-- L["FAQ_TEXT"] = [=[
|cffffd200
When I try to create a route, it says no data is found. What am I doing wrong?
|r
It means exactly that: No data is found, mostly because the addon is not loaded or in standby mode. If you are using any of the |cffffff78Cartographer_<Profession>|r modules, then these modules must be loaded and active for data to be available.

Note that |cffffff78Cartographer_<Profession>|r modules are all Load on Demand addons and require |cffffff78Cartographer_Professions|r to be enabled as it is the loading stub.

|cffffd200
I made a route with Rich Adamantite Ore in it. When I find normal Adamantite Ore in the same place, GatherMate/Cartographer deletes the rich node and replaces it with a normal node. This removes the node from my route since it is contructed out of only rich nodes. What can I do?
|r
1. You can make a route with both rich and normal Adamantite Ore in it.

2. You can tell Routes not to automatically insert/delete nodes. This option is found in the root options of the Routes tree in the config screen.

|cffffd200
Can you make a progress indicator on how long a background route optimization would take?
|r
A progress bar is not possible for the optimization process as it is a non-linear algorithm. It works on a "multiple pass" basis, each pass improving on the previous pass until it reaches a point where the improvement made is too minimal and then it will stop.

This is somewhat like the |cffffff78Windows XP Disk Defragmentation|r utility, and its progress bar is worthless because its only showing you the % of each pass, but it doesn't know how many passes it will take, it could be 3 passes, it could be 10 passes, it stops only when it thinks it has done enough. This is why in the |cffffff78Vista|r version, it no longer shows you a progress bar at all.

|cffffd200
How does Routes perform its route optimization?
|r
Routes uses an algorithm called |cffffff78Ant Colony Optimization|r (ACO) which is a heuristic/probabilistic method of calculating optimal graphs based on observed real life ant behavior.

ACO algorithms have been used to produce near-optimal solutions to the |cffffff78Traveling Salesman Problem|r (TSP). For more information, consult Google or Wikipedia.

|cffffd200
What does the "Extra Optimization" option do?
|r
By default, we only used ACO along with the standard |cffffff782-opt algorithm|r to optimize routes. Turning on "extra optimization" tells Routes to also use 2.5-opt, which is a specific subset of 3-opt. 2-opt is the process where pairs of edges are exchanged (A-B and C-D becomes A-C and B-D) in order to produce shorter routes.

|cffffd200
What algorithm does node clustering use?
|r
We employ a Hierarchical Agglomerative Clustering algorithm using a greedy approach, so the output is deterministic.

|cffffd200
I created a taboo region, attached it to a route, and optimized it. My route still flies through the taboo region. Why?
|r
It is not possible to always find a route that does not fly through a taboo region or sometimes highly unfeasible to do so.

The user could potentially create taboo regions that split the map into impassable sections and regions, so the algorithm is simply biased not to pass through them if it is possible.

|cffffd200
I've found a bug! Where do I report it?
|r
You can report bugs or give suggestions at |cffffff78http://forums.wowace.com/showthread.php?t=10369|r

Alternatively, you can also find us on |cffffff78irc://irc.freenode.org/wowace|r

When reporting a bug, make sure you include the |cffffff78steps on how to reproduce the bug|r, supply any |cffffff78error messages|r with stack traces if possible, give the |cffffff78revision number|r of Routes the problem occured in and state whether you are using an |cffffff78English client or otherwise|r.

|cffffd200
Who wrote this cool addon?
|r
|cffffff78Xaros|r on EU Doomhammer Alliance & |cffffff78Xinhuan|r on US Blackrock Alliance did.
]=]
L["Fishing"] = "Рыбалка"
-- L["Foreground"] = "Foreground"
-- L["Foreground Disclaimer"] = "Generate close to optimal path for the set of nodes in this route. Please keep in mind that doing this will 'hang' your client for some time. Depending on the amount of nodes (more cause near exponential increase in time) and CPU speed you might even get a disconnect if it takes too long."
L["Frequently Asked Questions"] = "Часто Зазадаваемые Вопросы"
L["GathererHERB"] = "Травничество"
L["GathererMINE"] = "Горное дело"
L["GathererOPEN"] = "Сокровища"
L["GatherMate2Archaeology"] = "Археология"
L["GatherMate2Extract Gas"] = "Извлечение газа"
L["GatherMate2Fishing"] = "Рыболовство"
L["GatherMate2Herb Gathering"] = "Травничество"
-- L["GatherMate2Logging"] = "GatherMate2Logging"
L["GatherMate2Mining"] = "Горное дело"
L["GatherMate2Treasure"] = "Сокровища"
L["Help File"] = "Файл помощи"
L["Herbalism"] = "Травничество"
L["Hidden route"] = "Скрытый маршрут"
L["Hide Route"] = "Скрыть маршрут"
L["Hide the route from being shown on the maps"] = "Скрыть маршрут из отображаемых сейчас на  картах"
L["Information"] = "Информация"
L["Integrated support options for TomTom"] = "Настройки встроенной поддержки для TomTom"
L["Line Color"] = "Цвет линии"
L["Line gaps"] = "Пробелы линии"
L["Line Settings"] = "Настройки линии"
L["Map Drawing"] = "Прорисовка карты"
L["Minimap"] = "Миникарта"
L["Minimap drawing"] = "Прорисовка миникарты"
L["Minimap when indoors"] = "Миникарта внутри зданий"
L["Mining"] = "Горное дело"
L["Name of Route"] = "Название маршрута"
L["Name of Taboo"] = "Имя запрещенной зоны"
L["Name of taboo region to add"] = "Имя запрещенной зоны для добавления"
L["Name of the route to add"] = "Имя маршрута для добавления"
L["Never show"] = "Никогда не показывать"
L["No data found"] = "Данные не найдены"
L["No data selected for new route"] = "Нет данных для нового маршрута"
L["No name given for new route"] = "Не введено имя нового маршрута"
L["No name given for new taboo region"] = "Не введено имя новой запретной зоны"
L["Normal lines"] = "Нормальные линии"
L["Note"] = "Примечание"
L["Now running TSP in the background..."] = "Сейчас оптимизация запущена в фоне...."
L["Only while tracking"] = "Только при слежении"
L["Only with profession"] = "Только для профессии"
L["Optimize Route"] = "Оптимизировать маршрут"
L["Optimizing a route"] = "Оптимизация маршрута"
-- L["OPTIMIZING_ROUTE_TEXT"] = [=[
New routes that are created start off unoptimized and just look like a haphazard mess of lines on the map. To optimize a route, navigate to your route on the left side. On the right side, there are 4 tabs, click on |cffffff78Optimize Route|r.

Route optimization has 2 parts. The first is Route Clustering, the second is Route Optimizing.

|cffffff781.|r Click the |cffffff78Cluster|r button to cluster the route.

|cffffff782.|r Click the |cffffff78Foreground|r OR |cffffff78Background|r button and wait.


|cffffd200Notes:|r

* Route clustering is optional. What it does is it takes nodes that are near each other within a specified distance and combines them into a single travel point. Clustering a route is a reversible process, no node data is lost.

* Route optimization can be done either using foreground or the background options. Both methods are identical. The foreground method will use up all your available CPU time "hanging WoW" until it completes, while the background method does it much more slowly in the background without locking WoW.

* Generally speaking, use foreground if the number of nodes is small (less than 100), background if the number of nodes is big, otherwise you risk disconnecting from the WoW servers if optimization takes too long.

* Route generation uses an algorithm known as |cffffff78Ant Colony Optimization|r. This algorithm is based on observed real life ant behavior, and uses thousands of random numbers to simulate the ants and generate the routes.

* This means that route generation is random and optimizing the same initial route will give different results each time. You may repeatedly optimize a route in an attempt to find a better solution, Routes will not discard a shorter known solution.

* The other reason why we want the generated route to be random is because you don't want 1000 other people to have the exact same route as you right? Standard WowHead node data is downloadable fairly easily for the 3 gathering addons.

* In its current implementation in Routes, the ACO algorithm is pruned fairly heavily in order to reduce execution time. Trying to solve an NP-Complete problem in a WoW sandbox using the Lua scripting language isn't the most ideal of things to do.

* We make efforts to prevent the route from criss-crossing itself, but sometimes it happens and the algorithm doesn't catch it. If this happens, just optimize the route again.
]=]
L["Options"] = "Настройки"
L["Overview"] = "Обзор"
L["OVERVIEW_TEXT"] = [=[ |cffffff78Routes|r это дополнение разработанное для того, чтобы сделать сбор ресурсов более эффективным. Это достигается созданием эффективных путей сбора того, что Вы хотите собрать используя существующие данные из дополнений |cffffff78GatherMate|r, |cffffff78Cartographer_<Profs>|r или |cffffff78Gatherer|r. Эти маршруты отображаются на Ваших картах, что позволяет Вам легко и быстро следовать по ним.

Задача |cffffff78Travelling Salesman Problem|r (TSP) это традиционная задача где дано N городов и даны расстояния между любыми двумя из них, Ваша задача отыскать кратчайший путь для однократного посещения всех городов и вернуться в начальный город. Такая же задача применима к узлам сбора в World of Warcraft для нахождения кратчайшего из возможных маршрутов для посещения каждого узла сбора в цепочке.
]=]
L["Pass %d: %d%%"] = "Проход %d: %d%%"
L["Pass %d: %d%% - %d yards"] = "Проход %d: %d%% - %d ярдов"
L["Path with %d nodes found with length %.2f yards after %d iterations in %.2f seconds."] = "Путь длиной %.2f ярдов из %d узлов  найден после %d итераций за %.2f  секунд."
L["Permanently delete a route"] = "Навсегда удалить маршрут"
L["Recreate Route"] = "Пересоздать маршрут"
L["Recreate this route with the same creation settings. NOTE: This only works for data from GatherMate2 and Gatherer."] = "Пересоздать этот маршрут с теми же настройкамми. ПРИМИЧАНИЕ: Это работает только с данными GatherMate2 и Gatherer."
L["Reset"] = "Сброс"
-- L["Reset the line settings to defaults"] = "Reset the line settings to defaults"
-- L["Route Clustering"] = "Route Clustering"
-- L["Route Optimizing"] = "Route Optimizing"
-- L["ROUTE_EDIT_DESC"] = [=[
To edit a route, click on the |cffffd200Edit|r button. The route will be drawn on the World Map. Drag the nodes to position them, left click on an in-between vertex to add nodes, right click on them to delete. After editing, you may click the |cffffd200Save|r button to save your changes, or the |cffffd200Cancel|r button to discard your changes.

Please note that you cannot edit a route when it is being optimized in the background or if the route is a clustered route.
]=]
-- L["Routes"] = "Routes"
L["routes"] = "маршруты"
-- L["Routes in %s"] = "Routes in %s"
-- L["Routes Node Menu"] = "Routes Node Menu"
L["Routes with Archaeology"] = "Маршруты с архиологией"
-- L["Routes with Fish"] = "Routes with Fish"
-- L["Routes with Gas"] = "Routes with Gas"
-- L["Routes with Herbs"] = "Routes with Herbs"
-- L["Routes with Notes"] = "Routes with Notes"
L["Routes with Ore"] = "Маршруты сбора руды"
L["Routes with Treasure"] = "Маршруты сбора сокровищ"
L["Save route edit"] = "Сохранить изменения маршрута"
L["Save taboo edit"] = "Сохранить изменения запрета"
L["Select data to use"] = "Выберите, какие данные использовать"
L["Select data to use in the route creation"] = "Выберите, какие данные использовать для создания маршрута"
L["Select sources of data"] = "Выберите источники данных"
L["Select taboo regions to apply:"] = "Выберите области запрета для:"
L["Select Zone"] = "Выбрать зону"
L["Set the width of lines on each of the maps."] = "Установите толщину линий для всех типов карт."
L["Shorten the lines drawn on the minimap slightly so that they do not overlap the icons and minimap tracking blips."] = "Укоротите линии на миникарте так, чтобы они не перекрывали значки и точки слежения."
L["Show hidden routes"] = "Отображать скрытые маршруты"
L["Show hidden routes?"] = "Отобразить скрытые маршруты?"
L["Skill-Engineering"] = "Навык-Инженерия"
L["Skill-Fishing"] = "Навык-Рыбная ловля"
L["Skill-Herbalism"] = "Навык-Травничество"
L["Skill-Mining"] = "Навык-Горное дело"
-- L["Skip clustered node points"] = "Skip clustered node points"
-- L["Start using TomTom"] = "Start using TomTom"
-- L["Start using TomTom by finding the closest visible route/node in the current zone and using that as the waypoint"] = "Start using TomTom by finding the closest visible route/node in the current zone and using that as the waypoint"
-- L["Start using Waypoints (TomTom)"] = "Start using Waypoints (TomTom)"
-- L["Stop editing this route on the world map and abandon changes made"] = "Stop editing this route on the world map and abandon changes made"
-- L["Stop editing this route on the world map and save the edits"] = "Stop editing this route on the world map and save the edits"
-- L["Stop editing this taboo region on the world map and abandon changes made"] = "Stop editing this taboo region on the world map and abandon changes made"
-- L["Stop editing this taboo region on the world map and save the edits"] = "Stop editing this taboo region on the world map and save the edits"
-- L["Stop using TomTom"] = "Stop using TomTom"
-- L["Stop using TomTom by clearing the last queued node"] = "Stop using TomTom by clearing the last queued node"
-- L["Stop using Waypoints (TomTom)"] = "Stop using Waypoints (TomTom)"
-- L["TABOO_DESC"] = "Taboo regions are areas which you can define to exclude nodes. Once you have created a taboo region, you can attach the taboo region to an existing route, and all nodes inside this region will be removed and no new ones will be added to it."
-- L["TABOO_DESC2"] = "Taboo regions are areas you specify for a route to ignore. Nodes in these taboo regions are ignored and not included in a route. Additionally when optimizing a route, the generated route will attempt to avoid crossing any taboo regions if possible."
-- L["TABOO_EDIT_DESC"] = "To edit a taboo region, click on the |cffffd200Edit|r button. The taboo region will be drawn on the World Map. Drag the vertexes to position them. Right click on the vertexes to add or delete vertexes. After editing, you may click the |cffffd200Save|r button to save your changes, or the |cffffd200Cancel|r button to discard your changes."
L["Taboos"] = "Запретные зоны"
L["Taboos in %s"] = "Запретные зоны в %s"
-- L["The cluster radius of this route is |cffffd200%d|r yards."] = "The cluster radius of this route is |cffffd200%d|r yards."
L["The following error occured in the background path generation coroutine, please report to Grum or Xinhuan:"] = "Во время работы процедуры создания маршрута произошла ошибка, пожалуйста сообщите об этом Grum или Xinhuan:"
L["There is already a TSP running in background. Wait for it to complete first."] = "Процедура оптимизации уже запущена в фоне. Сначала дождитесь её окончания."
-- L["These settings control the visibility and look of the drawn route."] = "These settings control the visibility and look of the drawn route."
L["This route contains |cffffd200%d|r nodes that have been tabooed."] = "Это маршрут содержит |cffffd200%d|r, которые запрещены."
L["This route contains the following nodes:"] = "Это маршрут содержит следующие узлы:"
-- L["This route has |cffffd200%d|r nodes and is |cffffd200%d|r yards long."] = "This route has |cffffd200%d|r nodes and is |cffffd200%d|r yards long."
L["This route has no taboo regions."] = "Это маршрут не содержит запретных областей."
-- L["This route has nodes that belong to the following categories:"] = "This route has nodes that belong to the following categories:"
L["This route has the following taboo regions:"] = "Это маршрут содержит запрещенные зоны:"
-- L["This route is a clustered route, down from the original |cffffd200%d|r nodes."] = "This route is a clustered route, down from the original |cffffd200%d|r nodes."
-- L["This route is not a clustered route."] = "This route is not a clustered route."
-- L[ [=[This section implements TomTom support for Routes. Click Start to find the nearest node in a visible route in the current zone.
]=] ] = [=[This section implements TomTom support for Routes. Click Start to find the nearest node in a visible route in the current zone.
]=]
-- L["Toggle drawing on each of the maps."] = "Toggle drawing on each of the maps."
L["TomTom is missing or disabled"] = "TomTom не установлен или заблокирован"
-- L["TOO_MANY_NODES_ERROR"] = "This route has more than 724 nodes. Please reduce it by removing some nodes or by clustering otherwise memory allocation errors will occur."
-- L["Treasure"] = "Treasure"
-- L["Uncluster"] = "Uncluster"
-- L["Uncluster this route"] = "Uncluster this route"
-- L["Update distance"] = "Update distance"
-- L["Use Auto Show/Hide"] = "Use Auto Show/Hide"
-- L["Waypoints (TomTom)"] = "Waypoints (TomTom)"
-- L["Waypoints Integration"] = "Waypoints Integration"
-- L["WAYPOINTS_INTEGRATION_TEXT"] = [=[
Routes comes with direct support for |cffffff78Cartographer_Waypoints|r or |cffffff78TomTom|r, using the waypoints system so that you can quickly travel along your routes without getting lost amidst the lines.

Using waypoints is easy. Simply go to a zone with a visible route, and click the |cffffff78Start using waypoints|r button. This tells Routes to find the closest node in the closest visible route and queues this node in |cffffff78Cartographer_Waypoints|r or |cffffff78TomTom|r. A graphical arrow then appears in the middle of the screen indicating the direction and distance to reach the waypoint.

When you reach the node, Routes will automatically queue the next node in the route and so on. Click |cffffff78Stop using waypoints|r to remove the currently queued node and |cffffff78Change directions|r to change the direction of nodes that are being queued.

To help with using waypoints, you can easily setup keybinds to start/stop and change directions in the Routes configuration screen itself or in ESC -> Key Bindings. Additionally, |cffffff78FuBar_RoutesFu|r has quick access menus for this as well.


|cffffd200Notes:|r

* The waypoint integration modules are disabled if the support addons are not found.
]=]
-- L["When the following data sources add or delete node data, update my routes automatically by inserting or removing the same node in the relevant routes."] = "When the following data sources add or delete node data, update my routes automatically by inserting or removing the same node in the relevant routes."
L["Width (Map)"] = "Ширина (Карта)"
L["Width (Minimap)"] = "Ширина (мини-карта)"
L["Width (Zone Map)"] = "Ширина (карта зоны)"
L["Width of the line in the map"] = "Ширина линии на карте"
L["Width of the line in the Minimap"] = "Ширина линии на мини-карте"
L["Width of the line in the Worldmap"] = "Ширина линии на карте мира"
L["Width of the line in the Zone Map"] = "Ширина линии на карте зоны"
L["Worldmap"] = "Карта мира"
L["Worldmap drawing"] = "Отрисовка карты мира"
L["Yards to move before triggering a minimap update"] = "Метров в пути до обновления мини-карты"
L["You have |cffffd200%d|r route(s) in |cffffd200%s|r."] = "У вас |cffffd200%d|r маршрут(ов) в |cffffd200%s|r."
L["You have |cffffd200%d|r taboo region(s) in |cffffd200%s|r."] = "У вас |cffffd200%d|r запретных областей в |cffffd200%s|r."
L["You may not delete a route that is being optimized in the background."] = "Вы не можете удалить оптимизирующийся маршрут."
L["You may not delete a taboo that is being edited."] = "Вы не можете удалить редактируемый запрет."
L["Zone Map"] = "Карта зоны"
L["Zone Map drawing"] = "Отрисовка карты зоны"
L["Zone to create route in"] = "Зона для создания маршрута"
L["Zone to create taboo in"] = "Зона для создания запрета"
