local AddOnFolderName, private = ...

local L = _G.LibStub("AceLocale-3.0"):NewLocale(AddOnFolderName, "enUS", true, false)
if not L then return end

L["Alerts"] = true
L["BOTTOM"] = "Bottom"
L["BOTTOMLEFT"] = "Bottom Left"
L["BOTTOMRIGHT"] = "Bottom Right"
L["CENTER"] = "Center"
L["Completed Achievement Criteria"] = true
L["Completed Quest Objectives"] = true
L["Detection"] = true
L["Drag to set the spawn point for targeting buttons."] = true
L["Duration"] = true
L["Hide Anchor"] = true
L["Horizontal offset from the anchor point."] = true
L["Ignore Mute"] = true
L["Interval"] = true
L["LEFT"] = "Left"
L["NPCs"] = true
L["Play alert sounds when sound is muted."] = true
L["Reset Position"] = true
L["RIGHT"] = "Right"
L["Screen Flash"] = true
L["Screen Location"] = true
L["Show Anchor"] = true
L["Spawn Point"] = true
L["The number of minutes a targeting button will exist before fading out."] = true
L["The number of minutes before an NPC will be detected again."] = true
L["TOP"] = "Top"
L["TOPLEFT"] = "Top Left"
L["TOPRIGHT"] = "Top Right"
L["Vertical offset from the anchor point."] = true
L["X Offset"] = true
L["Y Offset"] = true
L["Vignette/Aarkos - Looted Treasure"] = "Aarkos - Looted Treasure"
L["Vignette/Abandoned Fishing Pole"] = "Abandoned Fishing Pole"
L["Vignette/Alpha Bat"] = "Alpha Bat"
L["Vignette/Amateur Hunters"] = "Amateur Hunters"
L["Vignette/Anchorite's Sojourn"] = "Anchorite's Sojourn"
L["Vignette/Avatar of Sothrecar"] = "Avatar of Sothrecar"
L["Vignette/Beastmaster Pao'lek"] = "Beastmaster Pao'lek"
L["Vignette/BH Master Scout"] = "BH Master Scout"
L["Vignette/Blood Moon Boss"] = "Blood Moon Boss"
L["Vignette/Burning Front"] = "Burning Front"
L["Vignette/Cache of Infernals"] = "Cache of Infernals"
L["Vignette/Cave Keeper"] = "Cave Keeper"
L["Vignette/Cindral"] = "Cindral"
L["Vignette/Coldstomp"] = "Coldstomp"
L["Vignette/Coura, Master of Arcana"] = "Coura, Master of Arcana"
L["Vignette/Dead Orc Captain"] = "Dead Orc Captain"
L["Vignette/Dorg"] = "Dorg"
L["Vignette/Embaari Defense Crystal"] = "Embaari Defense Crystal"
L["Vignette/Enavra Varandi"] = "Enavra Varandi"
L["Vignette/Fel Saberon Shaman"] = "Fel Saberon Shaman"
L["Vignette/Foreling Worship Circle"] = "Foreling Worship Circle"
L["Vignette/Forsaken Deathsquad"] = "Forsaken Deathsquad"
L["Vignette/Frenzied Animus"] = "Frenzied Animus"
L["Vignette/Giant Python"] = "Giant Python"
L["Vignette/Giant Raptor"] = "Giant Raptor"
L["Vignette/Giantstalker Hunting Party"] = "Giantstalker Hunting Party"
L["Vignette/Giblette the Cowardly"] = "Giblette the Cowardly"
L["Vignette/Gorger the Hungry"] = "Gorger the Hungry"
L["Vignette/Haakun, The All-Consuming"] = "Haakun, The All-Consuming"
L["Vignette/Helmouth Raiders"] = "Helmouth Raiders"
L["Vignette/Hook & Sinker"] = "Hook & Sinker"
L["Vignette/Horn of the Siren"] = "Horn of the Siren"
L["Vignette/Houndmaster Jax'zor"] = "Houndmaster Jax'zor"
L["Vignette/IH Elite Sniper"] = "IH Elite Sniper"
L["Vignette/Invasion Point: Devastation"] = "Invasion Point: Devastation"
L["Vignette/Iron Front Captain 1"] = "Iron Front Captain 1"
L["Vignette/Iron Front Captain 2"] = "Iron Front Captain 2"
L["Vignette/Iron Front Captain 3"] = "Iron Front Captain 3"
L["Vignette/Iron Houndmaster"] = "Iron Houndmaster"
L["Vignette/Iron Tunnel Foreman"] = "Iron Tunnel Foreman"
L["Vignette/Kenos the Unraveller"] = "Kenos the Unraveller"
L["Vignette/Krahl Deathwind"] = "Krahl Deathwind"
L["Vignette/Lava-Gorged Goren"] = "Lava-Gorged Goren"
L["Vignette/Light the Braziers"] = "Light the Braziers"
L["Vignette/Lost Ettin"] = "Lost Ettin"
L["Vignette/Mandrakor the Night Hunter"] = "Mandrakor the Night Hunter"
L["Vignette/Murktide Alpha"] = "Murktide Alpha"
L["Vignette/Night Haunter"] = "Night Haunter"
L["Vignette/Oasis Icemother"] = "Oasis Icemother"
L["Vignette/Ogre Primalist"] = "Ogre Primalist"
L["Vignette/Pale Assassin"] = "Pale Assassin"
L["Vignette/Pale Gone Fishin'"] = "Pale Gone Fishin'"
L["Vignette/Pale Spider Broodmother"] = "Pale Spider Broodmother"
L["Vignette/Panther Saberon Boss"] = "Panther Saberon Boss"
L["Vignette/Perrexx the Corruptor"] = "Perrexx the Corruptor"
L["Vignette/Pit-Slayer"] = "Pit-Slayer"
L["Vignette/Protectors of the Grove"] = "Protectors of the Grove"
L["Vignette/Purging the River"] = "Purging the River"
L["Vignette/Ravager Broodlord"] = "Ravager Broodlord"
L["Vignette/Rogond"] = "Rogond"
L["Vignette/Saberon Blademaster"] = "Saberon Blademaster"
L["Vignette/Saberon Shaman"] = "Saberon Shaman"
L["Vignette/Sea Giant King"] = "Sea Giant King"
L["Vignette/Sea Hydra"] = "Sea Hydra"
L["Vignette/Sea Lord Torglork"] = "Sea Lord Torglork"
L["Vignette/Seek & Destroy Squad"] = "Seek & Destroy Squad"
L["Vignette/Shadowflame Terror"] = "Shadowflame Terror"
L["Vignette/Shadowmoon Cultist Ritual"] = "Shadowmoon Cultist Ritual"
L["Vignette/Shaman Fire Stone"] = "Shaman Fire Stone"
L["Vignette/Shivering Ashmaw Cub"] = "Shivering Ashmaw Cub"
L["Vignette/Skog"] = "Skog"
L["Vignette/Slogtusk the Corpse Eater"] = "Slogtusk the Corpse Eater"
L["Vignette/Stoneshard Broodmother"] = "Stoneshard Broodmother"
L["Vignette/Stormdrake Matriarch"] = "Stormdrake Matriarch"
L["Vignette/Syphonus & Leodrath"] = "Syphonus & Leodrath"
L["Vignette/Szirek"] = "Szirek"
L["Vignette/Thane's Mead Hall"] = "Thane's Mead Hall"
L["Vignette/The Beastly Boxer"] = "The Beastly Boxer"
L["Vignette/The Voidseer"] = "The Voidseer"
L["Vignette/Trecherous Stallions"] = "Trecherous Stallions"
L["Vignette/Undgrell Attack"] = "Undgrell Attack"
L["Vignette/Venomshade (Plant Hydra)"] = "Venomshade (Plant Hydra)"
L["Vignette/Wakkawam"] = "Wakkawam"
L["Vignette/Wandering Vindicator - Looted Treasure"] = "Wandering Vindicator - Looted Treasure"
L["Vignette/Worgen Stalkers"] = "Worgen Stalkers"
L["Vignette/Worg Pack"] = "Worg Pack"
L["Vignette/Xothear, The Destroyer"] = "Xothear, The Destroyer"
L["Vignette/Yggdrel the Corrupted"] = "Yggdrel the Corrupted"
L["Vignette/Zoug"] = "Zoug"
L["Vignette/Zulk"] = "Zulk"


local VL = _G.LibStub("AceLocale-3.0"):NewLocale(AddOnFolderName .. "Vignette", "enUS", true, false)
if not VL then return end

VL["Aarkos - Looted Treasure"] = true
VL["Abandoned Fishing Pole"] = true
VL["Alpha Bat"] = true
VL["Amateur Hunters"] = true
VL["Anchorite's Sojourn"] = true
VL["Avatar of Sothrecar"] = true
VL["Beastmaster Pao'lek"] = true
VL["BH Master Scout"] = true
VL["Blood Moon Boss"] = true
VL["Burning Front"] = true
VL["Cache of Infernals"] = true
VL["Cave Keeper"] = true
VL["Cindral"] = true
VL["Coldstomp"] = true
VL["Coura, Master of Arcana"] = true
VL["Dead Orc Captain"] = true
VL["Dorg"] = true
VL["Embaari Defense Crystal"] = true
VL["Enavra Varandi"] = true
VL["Fel Saberon Shaman"] = true
VL["Foreling Worship Circle"] = true
VL["Forsaken Deathsquad"] = true
VL["Frenzied Animus"] = true
VL["Giant Python"] = true
VL["Giant Raptor"] = true
VL["Giantstalker Hunting Party"] = true
VL["Giblette the Cowardly"] = true
VL["Gorger the Hungry"] = true
VL["Haakun, The All-Consuming"] = true
VL["Helmouth Raiders"] = true
VL["Hook & Sinker"] = true
VL["Horn of the Siren"] = true
VL["Houndmaster Jax'zor"] = true
VL["IH Elite Sniper"] = true
VL["Invasion Point: Devastation"] = true
VL["Iron Front Captain 1"] = true
VL["Iron Front Captain 2"] = true
VL["Iron Front Captain 3"] = true
VL["Iron Houndmaster"] = true
VL["Iron Tunnel Foreman"] = true
VL["Kenos the Unraveller"] = true
VL["Krahl Deathwind"] = true
VL["Lava-Gorged Goren"] = true
VL["Light the Braziers"] = true
VL["Lost Ettin"] = true
VL["Mandrakor the Night Hunter"] = true
VL["Murktide Alpha"] = true
VL["Night Haunter"] = true
VL["Oasis Icemother"] = true
VL["Ogre Primalist"] = true
VL["Pale Assassin"] = true
VL["Pale Gone Fishin'"] = true
VL["Pale Spider Broodmother"] = true
VL["Panther Saberon Boss"] = true
VL["Perrexx the Corruptor"] = true
VL["Pit-Slayer"] = true
VL["Protectors of the Grove"] = true
VL["Purging the River"] = true
VL["Ravager Broodlord"] = true
VL["Rogond"] = true
VL["Saberon Blademaster"] = true
VL["Saberon Shaman"] = true
VL["Sea Giant King"] = true
VL["Sea Hydra"] = true
VL["Sea Lord Torglork"] = true
VL["Seek & Destroy Squad"] = true
VL["Shadowflame Terror"] = true
VL["Shadowmoon Cultist Ritual"] = true
VL["Shaman Fire Stone"] = true
VL["Shivering Ashmaw Cub"] = true
VL["Skog"] = true
VL["Slogtusk the Corpse Eater"] = true
VL["Stoneshard Broodmother"] = true
VL["Stormdrake Matriarch"] = true
VL["Syphonus & Leodrath"] = true
VL["Szirek"] = true
VL["Thane's Mead Hall"] = true
VL["The Beastly Boxer"] = true
VL["The Voidseer"] = true
VL["Trecherous Stallions"] = true
VL["Undgrell Attack"] = true
VL["Venomshade (Plant Hydra)"] = true
VL["Wakkawam"] = true
VL["Wandering Vindicator - Looted Treasure"] = true
VL["Worgen Stalkers"] = true
VL["Worg Pack"] = true
VL["Xothear, The Destroyer"] = true
VL["Yggdrel the Corrupted"] = true
VL["Zoug"] = true
VL["Zulk"] = true

