local AddOnFolderName, private = ...
local L = _G.LibStub("AceLocale-3.0"):NewLocale(AddOnFolderName, "frFR")
if not L then return end

L["%1$s (%2$d) is already on the user-defined NPC list."] = "%1$s (%2$d) est déjà dans la liste des PNJ définis par l'utilisateur."
L["%1$s (%2$d) is not on the user-defined NPC list."] = "%1$s (%2$d) n'est pas dans la liste des PNJ définis par l'utilisateur."
L["Added %1$s (%2$d) to the user-defined NPC list."] = "%1$s (%2$d) a été ajouté à la liste des PNJ définis par l'utilisateur."
L["Alerts"] = "Alertes"
L["BOTTOM"] = "Bas"
L["BOTTOMLEFT"] = "Bas gauche"
L["BOTTOMRIGHT"] = "Bas droite"
L["CENTER"] = "Centre"
L["Completed Achievement Criteria"] = "Critères de hauts faits accomplis"
L["Completed Quest Objectives"] = "Objectifs de quêtes complétées"
--[[Translation missing --]]
--[[ L["Dead NPCs"] = "Dead NPCs"--]] 
L["Detection"] = "Détection"
L["Drag to set the spawn point for targeting buttons."] = "Faire glisser pour définir le lieu d'apparition des boutons de ciblage."
L["Duration"] = "Durée"
L["Hide Anchor"] = "Cacher l'ancre"
L["Hide During Combat"] = "Cacher en combat"
L["Horizontal offset from the anchor point."] = "Décalage horizontal du point d'ancrage."
L["Ignore Mute"] = "Ignorer la sourdine"
L["Interval"] = "Intervalle"
L["LEFT"] = "Gauche"
L["NPCs"] = "PNJs"
L["Play alert sounds when sound is muted."] = "Jouer les sons d'alerte quand le son du jeu est coupé."
L["Predefined NPCs cannot be added to or removed from the user-defined NPC list."] = "Les PNJs prédéfinis ne peuvent être ajouté ou retiré de la liste des PNJ définis par l'utilisateur."
L["Removed %1$s (%2$d) from the user-defined NPC list."] = "%1$s (%2$d) retiré de la liste des PNJ définis par l'utilisateur."
L["Reset Position"] = "Réinitialiser postition"
L["RIGHT"] = "Droite"
L["Screen Flash"] = "Clignotement de l'écran"
L["Screen Location"] = "Positionnement"
L["Show Anchor"] = "Afficher l'ancre"
L["Spawn Point"] = "Point d'apparition"
L["The number of minutes a targeting button will exist before fading out."] = "Le nombre de minutes pendant lesquelles un bouton de ciblage existera avant de disparaître."
L["The number of minutes before an NPC will be detected again."] = "Le nombre de minutes avant que le même PNJ ne soit détecté de nouveau."
L["TOP"] = "Haut"
L["TOPLEFT"] = "Haut gauche"
L["TOPRIGHT"] = "Haut droit"
--[[Translation missing --]]
--[[ L["Type the name of a Continent, Dungeon, or Zone, or the partial name of an NPC. Accepts Lua patterns."] = "Type the name of a Continent, Dungeon, or Zone, or the partial name of an NPC. Accepts Lua patterns."--]] 
--[[Translation missing --]]
--[[ L["Valid values are a numeric NPC ID, the word \"mouseover\" while you have your mouse cursor over an NPC, or the word \"target\" while you have an NPC set as your target."] = "Valid values are a numeric NPC ID, the word \"mouseover\" while you have your mouse cursor over an NPC, or the word \"target\" while you have an NPC set as your target."--]] 
L["Vertical offset from the anchor point."] = "Décalage vertical du point d'ancrage."
L["X Offset"] = "Décalage sur X"
L["Y Offset"] = "Décalage sur Y"


local VL = _G.LibStub("AceLocale-3.0"):NewLocale(AddOnFolderName .. "Vignette", "frFR")
if not VL then return end

-- Vignette
VL["Aarkos - Looted Treasure"] = "Trésor de la famille d’Aarko"
VL["Abandoned Fishing Pole"] = "Canne à pêche abandonnée"
VL["Alpha Bat"] = "Chauve-souris Alpha"
VL["Amateur Hunters"] = "Chasseurs amateurs"
VL["Ambassador D'vwinn"] = "Ambassadeur D'vwinn"
VL["Anax"] = "Anax"
VL["Anchorite's Sojourn"] = "Séjour de l'Anachorète"
--[[Translation missing --]]
--[[ VL["Antydas Nightcaller's Hideaway"] = "Antydas Nightcaller's Hideaway"--]] 
--[[Translation missing --]]
--[[ VL["Apothecary Faldren"] = "Apothecary Faldren"--]] 
--[[Translation missing --]]
--[[ VL["Arcanist Lylandre"] = "Arcanist Lylandre"--]] 
--[[Translation missing --]]
--[[ VL["Arcanist Shal'iman"] = "Arcanist Shal'iman"--]] 
--[[Translation missing --]]
--[[ VL["Artificer Lothaire"] = "Artificer Lothaire"--]] 
--[[Translation missing --]]
--[[ VL["Avatar of Sothrecar"] = "Avatar of Sothrecar"--]] 
--[[Translation missing --]]
--[[ VL["Bahagar"] = "Bahagar"--]] 
--[[Translation missing --]]
--[[ VL["Ba'ruun"] = "Ba'ruun"--]] 
--[[Translation missing --]]
--[[ VL["Battle of the Barnacle"] = "Battle of the Barnacle"--]] 
--[[Translation missing --]]
--[[ VL["Beacher"] = "Beacher"--]] 
VL["Beastmaster Pao'lek"] = "Belluaire Pao’lek"
--[[Translation missing --]]
--[[ VL["BH Master Scout"] = "BH Master Scout"--]] 
--[[Translation missing --]]
--[[ VL["Bilebrain"] = "Bilebrain"--]] 
--[[Translation missing --]]
--[[ VL["Bladesquall"] = "Bladesquall"--]] 
--[[Translation missing --]]
--[[ VL["Bodash the Hoarder"] = "Bodash the Hoarder"--]] 
--[[Translation missing --]]
--[[ VL["Brawlgoth"] = "Brawlgoth"--]] 
--[[Translation missing --]]
--[[ VL["Bristlemaul"] = "Bristlemaul"--]] 
--[[Translation missing --]]
--[[ VL["Brogrul the Mighty"] = "Brogrul the Mighty"--]] 
--[[Translation missing --]]
--[[ VL["Broodmother Lizax"] = "Broodmother Lizax"--]] 
VL["Cache of Infernals"] = "Cache d’infernaux"
--[[Translation missing --]]
--[[ VL["Cadraeus"] = "Cadraeus"--]] 
--[[Translation missing --]]
--[[ VL["Cailyn Paledoom"] = "Cailyn Paledoom"--]] 
--[[Translation missing --]]
--[[ VL["Captain Volo'ren"] = "Captain Volo'ren"--]] 
--[[Translation missing --]]
--[[ VL["Captured Survivor"] = "Captured Survivor"--]] 
--[[Translation missing --]]
--[[ VL["Cave Keeper"] = "Cave Keeper"--]] 
--[[Translation missing --]]
--[[ VL["Champion Chomper"] = "Champion Chomper"--]] 
--[[Translation missing --]]
--[[ VL["Charfeather"] = "Charfeather"--]] 
--[[Translation missing --]]
--[[ VL["Chief Bitterbrine"] = "Chief Bitterbrine"--]] 
--[[Translation missing --]]
--[[ VL["Cindral"] = "Cindral"--]] 
VL["Coldstomp"] = "Pied-Froid"
--[[Translation missing --]]
--[[ VL["Commander Soraax"] = "Commander Soraax"--]] 
--[[Translation missing --]]
--[[ VL["Cora'kar"] = "Cora'kar"--]] 
VL["Coura, Master of Arcana"] = "Coura, maîtresse des Arcanes"
--[[Translation missing --]]
--[[ VL["Crab Rider Grmlrml"] = "Crab Rider Grmlrml"--]] 
--[[Translation missing --]]
--[[ VL["Crawshuk the Hungry"] = "Crawshuk the Hungry"--]] 
--[[Translation missing --]]
--[[ VL["Crystalbeard"] = "Crystalbeard"--]] 
--[[Translation missing --]]
--[[ VL["Daggerbeak"] = "Daggerbeak"--]] 
--[[Translation missing --]]
--[[ VL["Darkshade, Saber Matriarch"] = "Darkshade, Saber Matriarch"--]] 
--[[Translation missing --]]
--[[ VL["Dead Orc Captain"] = "Dead Orc Captain"--]] 
--[[Translation missing --]]
--[[ VL["Devouring Darkness"] = "Devouring Darkness"--]] 
--[[Translation missing --]]
--[[ VL["Dorg"] = "Dorg"--]] 
--[[Translation missing --]]
--[[ VL["Dreadbog"] = "Dreadbog"--]] 
--[[Translation missing --]]
--[[ VL["Dread-Rider Cortis"] = "Dread-Rider Cortis"--]] 
--[[Translation missing --]]
--[[ VL["Echo of Murmur"] = "Echo of Murmur"--]] 
--[[Translation missing --]]
--[[ VL["Egyl the Enduring"] = "Egyl the Enduring"--]] 
--[[Translation missing --]]
--[[ VL["Elfbane"] = "Elfbane"--]] 
--[[Translation missing --]]
--[[ VL["Elindya Featherlight"] = "Elindya Featherlight"--]] 
--[[Translation missing --]]
--[[ VL["Embaari Defense Crystal"] = "Embaari Defense Crystal"--]] 
--[[Translation missing --]]
--[[ VL["Enavra Varandi"] = "Enavra Varandi"--]] 
--[[Translation missing --]]
--[[ VL["Faebright"] = "Faebright"--]] 
--[[Translation missing --]]
--[[ VL["Fathnyr"] = "Fathnyr"--]] 
--[[Translation missing --]]
--[[ VL["Fel Saberon Shaman"] = "Fel Saberon Shaman"--]] 
--[[Translation missing --]]
--[[ VL["Fenri"] = "Fenri"--]] 
--[[Translation missing --]]
--[[ VL["Flog the Captain-Eater"] = "Flog the Captain-Eater"--]] 
--[[Translation missing --]]
--[[ VL["Flotsam"] = "Flotsam"--]] 
--[[Translation missing --]]
--[[ VL["Foreling Worship Circle"] = "Foreling Worship Circle"--]] 
VL["Forsaken Deathsquad"] = "Escadron de la mort réprouvé"
--[[Translation missing --]]
--[[ VL["Frenzied Animus"] = "Frenzied Animus"--]] 
--[[Translation missing --]]
--[[ VL["Frostshard"] = "Frostshard"--]] 
--[[Translation missing --]]
--[[ VL["Galzomar"] = "Galzomar"--]] 
--[[Translation missing --]]
--[[ VL["Garvrulg"] = "Garvrulg"--]] 
--[[Translation missing --]]
--[[ VL["Gennadian"] = "Gennadian"--]] 
--[[Translation missing --]]
--[[ VL["Giant Python"] = "Giant Python"--]] 
--[[Translation missing --]]
--[[ VL["Giant Raptor"] = "Giant Raptor"--]] 
--[[Translation missing --]]
--[[ VL["Giantstalker Hunting Party"] = "Giantstalker Hunting Party"--]] 
--[[Translation missing --]]
--[[ VL["Giblette the Cowardly"] = "Giblette the Cowardly"--]] 
--[[Translation missing --]]
--[[ VL["Glimar Ironfist"] = "Glimar Ironfist"--]] 
--[[Translation missing --]]
--[[ VL["Gom Crabbar"] = "Gom Crabbar"--]] 
--[[Translation missing --]]
--[[ VL["Gorebeak"] = "Gorebeak"--]] 
--[[Translation missing --]]
--[[ VL["Gorger the Hungry"] = "Gorger the Hungry"--]] 
--[[Translation missing --]]
--[[ VL["Gorgroth"] = "Gorgroth"--]] 
--[[Translation missing --]]
--[[ VL["Grelda the Hag"] = "Grelda the Hag"--]] 
--[[Translation missing --]]
--[[ VL["Grrvrgull the Conquerer"] = "Grrvrgull the Conquerer"--]] 
--[[Translation missing --]]
--[[ VL["Guardian Thor'el"] = "Guardian Thor'el"--]] 
--[[Translation missing --]]
--[[ VL["Gurbog da Basher"] = "Gurbog da Basher"--]] 
--[[Translation missing --]]
--[[ VL["Haakun, The All-Consuming"] = "Haakun, The All-Consuming"--]] 
--[[Translation missing --]]
--[[ VL["Hannval the Butcher"] = "Hannval the Butcher"--]] 
--[[Translation missing --]]
--[[ VL["Har'kess the Insatiable"] = "Har'kess the Insatiable"--]] 
--[[Translation missing --]]
--[[ VL["Hartli the Snatcher"] = "Hartli the Snatcher"--]] 
--[[Translation missing --]]
--[[ VL["Haunted Manor"] = "Haunted Manor"--]] 
VL["Helmouth Raiders"] = "Écumeurs de l’embouchure de Hel"
--[[Translation missing --]]
--[[ VL["Hertha Grimdottir"] = "Hertha Grimdottir"--]] 
VL["Hook & Sinker"] = "Hameçon & Le Plomb"
VL["Horn of the Siren"] = "Cor des sirènes"
--[[Translation missing --]]
--[[ VL["Houndmaster Ely"] = "Houndmaster Ely"--]] 
--[[Translation missing --]]
--[[ VL["Houndmaster Jax'zor"] = "Houndmaster Jax'zor"--]] 
--[[Translation missing --]]
--[[ VL["Houndmaster Stroxis"] = "Houndmaster Stroxis"--]] 
--[[Translation missing --]]
--[[ VL["Huk'roth the Houndmaster"] = "Huk'roth the Houndmaster"--]] 
--[[Translation missing --]]
--[[ VL["IH Elite Sniper"] = "IH Elite Sniper"--]] 
--[[Translation missing --]]
--[[ VL["Inquisitor Ernstenbok"] = "Inquisitor Ernstenbok"--]] 
--[[Translation missing --]]
--[[ VL["Inquisitor Tivos"] = "Inquisitor Tivos"--]] 
--[[Translation missing --]]
--[[ VL["Inquisitor Volitix"] = "Inquisitor Volitix"--]] 
--[[Translation missing --]]
--[[ VL["Invasion Point: Devastation"] = "Invasion Point: Devastation"--]] 
--[[Translation missing --]]
--[[ VL["Iron Front Captain 1"] = "Iron Front Captain 1"--]] 
--[[Translation missing --]]
--[[ VL["Iron Front Captain 2"] = "Iron Front Captain 2"--]] 
--[[Translation missing --]]
--[[ VL["Iron Front Captain 3"] = "Iron Front Captain 3"--]] 
VL["Iron Houndmaster"] = "Maître-chien de Fer"
--[[Translation missing --]]
--[[ VL["Iron Tunnel Foreman"] = "Iron Tunnel Foreman"--]] 
--[[Translation missing --]]
--[[ VL["Ironbranch"] = "Ironbranch"--]] 
--[[Translation missing --]]
--[[ VL["Isel the Hammer"] = "Isel the Hammer"--]] 
--[[Translation missing --]]
--[[ VL["Ivory Sentinel"] = "Ivory Sentinel"--]] 
--[[Translation missing --]]
--[[ VL["Jade Darkhaven"] = "Jade Darkhaven"--]] 
--[[Translation missing --]]
--[[ VL["Jaluk the Pacifist"] = "Jaluk the Pacifist"--]] 
--[[Translation missing --]]
--[[ VL["Jetsam"] = "Jetsam"--]] 
--[[Translation missing --]]
--[[ VL["Kenos the Unraveller"] = "Kenos the Unraveller"--]] 
--[[Translation missing --]]
--[[ VL["Kethrazor"] = "Kethrazor"--]] 
--[[Translation missing --]]
--[[ VL["Kharazos the Triumphant"] = "Kharazos the Triumphant"--]] 
--[[Translation missing --]]
--[[ VL["Klikixx"] = "Klikixx"--]] 
--[[Translation missing --]]
--[[ VL["Kottr Vondyr"] = "Kottr Vondyr"--]] 
--[[Translation missing --]]
--[[ VL["Krahl Deathwind"] = "Krahl Deathwind"--]] 
--[[Translation missing --]]
--[[ VL["Lady Rivantas"] = "Lady Rivantas"--]] 
--[[Translation missing --]]
--[[ VL["Lava-Gorged Goren"] = "Lava-Gorged Goren"--]] 
--[[Translation missing --]]
--[[ VL["Leaf-Reader Kurri"] = "Leaf-Reader Kurri"--]] 
--[[Translation missing --]]
--[[ VL["Lieutenant Strathmar"] = "Lieutenant Strathmar"--]] 
--[[Translation missing --]]
--[[ VL["Light the Braziers"] = "Light the Braziers"--]] 
--[[Translation missing --]]
--[[ VL["Llorian"] = "Llorian"--]] 
VL["Lost Ettin"] = "Ettin perdu"
--[[Translation missing --]]
--[[ VL["Luggut the Eggeater"] = "Luggut the Eggeater"--]] 
--[[Translation missing --]]
--[[ VL["Lyrath Moonfeather"] = "Lyrath Moonfeather"--]] 
--[[Translation missing --]]
--[[ VL["Mad \"King\" Sporeon"] = "Mad \"King\" Sporeon"--]] 
--[[Translation missing --]]
--[[ VL["Magister Phaedris"] = "Magister Phaedris"--]] 
--[[Translation missing --]]
--[[ VL["Maia the White"] = "Maia the White"--]] 
--[[Translation missing --]]
--[[ VL["Majestic Elderhorn"] = "Majestic Elderhorn"--]] 
--[[Translation missing --]]
--[[ VL["Mal'Dreth the Corrupter"] = "Mal'Dreth the Corrupter"--]] 
--[[Translation missing --]]
--[[ VL["Mandrakor the Night Hunter"] = "Mandrakor the Night Hunter"--]] 
--[[Translation missing --]]
--[[ VL["Marius & Tehd"] = "Marius & Tehd"--]] 
--[[Translation missing --]]
--[[ VL["Mar'tura"] = "Mar'tura"--]] 
--[[Translation missing --]]
--[[ VL["Matron Hagatha"] = "Matron Hagatha"--]] 
--[[Translation missing --]]
--[[ VL["Mellok, Son of Torok"] = "Mellok, Son of Torok"--]] 
--[[Translation missing --]]
--[[ VL["Miasu"] = "Miasu"--]] 
--[[Translation missing --]]
--[[ VL["Mordvigbjorn"] = "Mordvigbjorn"--]] 
--[[Translation missing --]]
--[[ VL["Mother Om'ra"] = "Mother Om'ra"--]] 
--[[Translation missing --]]
--[[ VL["Mrrgrl the Tide Reaver"] = "Mrrgrl the Tide Reaver"--]] 
--[[Translation missing --]]
--[[ VL["Murktide Alpha"] = "Murktide Alpha"--]] 
--[[Translation missing --]]
--[[ VL["Myonix"] = "Myonix"--]] 
--[[Translation missing --]]
--[[ VL["Naroua, King of the Forest"] = "Naroua, King of the Forest"--]] 
--[[Translation missing --]]
--[[ VL["Nas Dunberlin"] = "Nas Dunberlin"--]] 
VL["Night Haunter"] = "Hante-la-Nuit"
--[[Translation missing --]]
--[[ VL["Noble Blademaster"] = "Noble Blademaster"--]] 
--[[Translation missing --]]
--[[ VL["No'losh"] = "No'losh"--]] 
--[[Translation missing --]]
--[[ VL["Normantis the Deposed"] = "Normantis the Deposed"--]] 
--[[Translation missing --]]
--[[ VL["Oasis Icemother"] = "Oasis Icemother"--]] 
--[[Translation missing --]]
--[[ VL["Ogre Primalist"] = "Ogre Primalist"--]] 
--[[Translation missing --]]
--[[ VL["Old Bear Trap"] = "Old Bear Trap"--]] 
--[[Translation missing --]]
--[[ VL["Oreth the Vile"] = "Oreth the Vile"--]] 
--[[Translation missing --]]
--[[ VL["Oubdob da Smasher"] = "Oubdob da Smasher"--]] 
--[[Translation missing --]]
--[[ VL["Pale Assassin"] = "Pale Assassin"--]] 
--[[Translation missing --]]
--[[ VL["Pale Gone Fishin'"] = "Pale Gone Fishin'"--]] 
--[[Translation missing --]]
--[[ VL["Pale Spider Broodmother"] = "Pale Spider Broodmother"--]] 
--[[Translation missing --]]
--[[ VL["Panther Saberon Boss"] = "Panther Saberon Boss"--]] 
VL["Perrexx the Corruptor"] = "Perrexx le Corrupteur"
--[[Translation missing --]]
--[[ VL["Pinchshank"] = "Pinchshank"--]] 
--[[Translation missing --]]
--[[ VL["Pit-Slayer"] = "Pit-Slayer"--]] 
--[[Translation missing --]]
--[[ VL["Pridelord Meowl"] = "Pridelord Meowl"--]] 
--[[Translation missing --]]
--[[ VL["Protectors of the Grove"] = "Protectors of the Grove"--]] 
VL["Purging the River"] = "Purge de la rivière"
--[[Translation missing --]]
--[[ VL["Quin'el, Master of Chillwind"] = "Quin'el, Master of Chillwind"--]] 
--[[Translation missing --]]
--[[ VL["Ragemaw"] = "Ragemaw"--]] 
--[[Translation missing --]]
--[[ VL["Randril"] = "Randril"--]] 
--[[Translation missing --]]
--[[ VL["Rauren"] = "Rauren"--]] 
--[[Translation missing --]]
--[[ VL["Ravager Broodlord"] = "Ravager Broodlord"--]] 
--[[Translation missing --]]
--[[ VL["Ravyn-Drath"] = "Ravyn-Drath"--]] 
--[[Translation missing --]]
--[[ VL["Really Skunky Beer"] = "Really Skunky Beer"--]] 
--[[Translation missing --]]
--[[ VL["Reef Lord Raj'his"] = "Reef Lord Raj'his"--]] 
--[[Translation missing --]]
--[[ VL["Remnant of the Blood Moon"] = "Remnant of the Blood Moon"--]] 
--[[Translation missing --]]
--[[ VL["Rogond"] = "Rogond"--]] 
--[[Translation missing --]]
--[[ VL["Rok'nash"] = "Rok'nash"--]] 
--[[Translation missing --]]
--[[ VL["Roteye"] = "Roteye"--]] 
--[[Translation missing --]]
--[[ VL["Saberon Blademaster"] = "Saberon Blademaster"--]] 
--[[Translation missing --]]
--[[ VL["Saberon Shaman"] = "Saberon Shaman"--]] 
--[[Translation missing --]]
--[[ VL["Sapper Vorick"] = "Sapper Vorick"--]] 
--[[Translation missing --]]
--[[ VL["Scout Harefoot"] = "Scout Harefoot"--]] 
--[[Translation missing --]]
--[[ VL["Sea Giant King"] = "Sea Giant King"--]] 
--[[Translation missing --]]
--[[ VL["Sea Hydra"] = "Sea Hydra"--]] 
--[[Translation missing --]]
--[[ VL["Sea King Tidross"] = "Sea King Tidross"--]] 
--[[Translation missing --]]
--[[ VL["Sea Lord Torglork"] = "Sea Lord Torglork"--]] 
VL["Seek & Destroy Squad"] = "Unité de recherche et d’élimination"
--[[Translation missing --]]
--[[ VL["Seemingly Unguarded Treasure"] = "Seemingly Unguarded Treasure"--]] 
--[[Translation missing --]]
--[[ VL["Seersei"] = "Seersei"--]] 
--[[Translation missing --]]
--[[ VL["Sekhan"] = "Sekhan"--]] 
--[[Translation missing --]]
--[[ VL["Selia, Master of Balefire"] = "Selia, Master of Balefire"--]] 
--[[Translation missing --]]
--[[ VL["Shadowflame Terror"] = "Shadowflame Terror"--]] 
--[[Translation missing --]]
--[[ VL["Shadowmoon Cultist Ritual"] = "Shadowmoon Cultist Ritual"--]] 
--[[Translation missing --]]
--[[ VL["Shadowquill"] = "Shadowquill"--]] 
--[[Translation missing --]]
--[[ VL["Shal'an"] = "Shal'an"--]] 
--[[Translation missing --]]
--[[ VL["Shaman Fire Stone"] = "Shaman Fire Stone"--]] 
--[[Translation missing --]]
--[[ VL["Shara Felbreath"] = "Shara Felbreath"--]] 
--[[Translation missing --]]
--[[ VL["Shinri"] = "Shinri"--]] 
VL["Shivering Ashmaw Cub"] = "Petit cendregueule tremblant"
--[[Translation missing --]]
--[[ VL["Siegemaster Aedrin"] = "Siegemaster Aedrin"--]] 
--[[Translation missing --]]
--[[ VL["Sikthiss, Maiden of Slaughter"] = "Sikthiss, Maiden of Slaughter"--]] 
--[[Translation missing --]]
--[[ VL["Skagg"] = "Skagg"--]] 
--[[Translation missing --]]
--[[ VL["Skog"] = "Skog"--]] 
--[[Translation missing --]]
--[[ VL["Skywhisker Taskmaster"] = "Skywhisker Taskmaster"--]] 
--[[Translation missing --]]
--[[ VL["Slogtusk"] = "Slogtusk"--]] 
--[[Translation missing --]]
--[[ VL["Slumbering Bear"] = "Slumbering Bear"--]] 
--[[Translation missing --]]
--[[ VL["Soulfang"] = "Soulfang"--]] 
--[[Translation missing --]]
--[[ VL["Soulgrinder Portal"] = "Soulgrinder Portal"--]] 
--[[Translation missing --]]
--[[ VL["Soulthirster"] = "Soulthirster"--]] 
--[[Translation missing --]]
--[[ VL["Starbuck"] = "Starbuck"--]] 
--[[Translation missing --]]
--[[ VL["Stingtail Nest"] = "Stingtail Nest"--]] 
--[[Translation missing --]]
--[[ VL["Stomper Kreego"] = "Stomper Kreego"--]] 
--[[Translation missing --]]
--[[ VL["Stoneshard Broodmother"] = "Stoneshard Broodmother"--]] 
--[[Translation missing --]]
--[[ VL["Stormwing Matriarch"] = "Stormwing Matriarch"--]] 
VL["Syphonus & Leodrath"] = "Syphonus et Léodrath"
VL["Szirek"] = "Szirek"
--[[Translation missing --]]
--[[ VL["Tarben"] = "Tarben"--]] 
VL["Thane's Mead Hall"] = "Grande salle du thane"
VL["The Beastly Boxer"] = "Le boxeur bestial"
--[[Translation missing --]]
--[[ VL["The Blightcaller"] = "The Blightcaller"--]] 
--[[Translation missing --]]
--[[ VL["The Brood Queen's Court: Count Nefarious"] = "The Brood Queen's Court: Count Nefarious"--]] 
--[[Translation missing --]]
--[[ VL["The Brood Queen's Court: General Volroth"] = "The Brood Queen's Court: General Volroth"--]] 
--[[Translation missing --]]
--[[ VL["The Brood Queen's Court: King Voras"] = "The Brood Queen's Court: King Voras"--]] 
--[[Translation missing --]]
--[[ VL["The Brood Queen's Court: Overseer Brutarg"] = "The Brood Queen's Court: Overseer Brutarg"--]] 
--[[Translation missing --]]
--[[ VL["The Exiled Shaman"] = "The Exiled Shaman"--]] 
--[[Translation missing --]]
--[[ VL["The Muscle"] = "The Muscle"--]] 
--[[Translation missing --]]
--[[ VL["The Nameless King"] = "The Nameless King"--]] 
--[[Translation missing --]]
--[[ VL["The Oracle"] = "The Oracle"--]] 
--[[Translation missing --]]
--[[ VL["The Voidseer"] = "The Voidseer"--]] 
--[[Translation missing --]]
--[[ VL["Theryssia"] = "Theryssia"--]] 
--[[Translation missing --]]
--[[ VL["Thondrax"] = "Thondrax"--]] 
--[[Translation missing --]]
--[[ VL["Tide Behemoth"] = "Tide Behemoth"--]] 
--[[Translation missing --]]
--[[ VL["Tideclaw"] = "Tideclaw"--]] 
--[[Translation missing --]]
--[[ VL["Torrentius"] = "Torrentius"--]] 
--[[Translation missing --]]
--[[ VL["Totally Safe Treasure Chest"] = "Totally Safe Treasure Chest"--]] 
VL["Trecherous Stallions"] = "Étalons félons"
--[[Translation missing --]]
--[[ VL["Unbound Rift"] = "Unbound Rift"--]] 
VL["Undgrell Attack"] = "Attaque de sous-grells"
--[[Translation missing --]]
--[[ VL["Unguarded Thistleleaf Treasure"] = "Unguarded Thistleleaf Treasure"--]] 
--[[Translation missing --]]
--[[ VL["Urgev the Flayer"] = "Urgev the Flayer"--]] 
--[[Translation missing --]]
--[[ VL["Valiyaka the Stormbringer"] = "Valiyaka the Stormbringer"--]] 
--[[Translation missing --]]
--[[ VL["Venomshade (Plant Hydra)"] = "Venomshade (Plant Hydra)"--]] 
--[[Translation missing --]]
--[[ VL["Vicious Whale Shark"] = "Vicious Whale Shark"--]] 
--[[Translation missing --]]
--[[ VL["Vorthax"] = "Vorthax"--]] 
VL["Wakkawam"] = "Wakkawam"
--[[Translation missing --]]
--[[ VL["Wandering Vindicator - Looted Treasure"] = "Wandering Vindicator - Looted Treasure"--]] 
--[[Translation missing --]]
--[[ VL["Whitewater Typhoon"] = "Whitewater Typhoon"--]] 
VL["Worg Pack"] = "Meute de worgs"
VL["Worgen Stalkers"] = "Traqueurs worgens"
--[[Translation missing --]]
--[[ VL["Wraithtalon"] = "Wraithtalon"--]] 
--[[Translation missing --]]
--[[ VL["Wrath-Lord Lekos"] = "Wrath-Lord Lekos"--]] 
--[[Translation missing --]]
--[[ VL["Xothear, The Destroyer"] = "Xothear, The Destroyer"--]] 
--[[Translation missing --]]
--[[ VL["Yggdrel"] = "Yggdrel"--]] 
VL["Zoug"] = "Zoug"
VL["Zulk"] = "Zulk"

