local AddOnFolderName = ...
local L = _G.LibStub("AceLocale-3.0"):NewLocale(AddOnFolderName, "ptBR")
if not L then return end

L["%1$s (%2$d) is already on the user-defined NPC list."] = "%1$s (%2$d) já está na lista de NPCs definida pelo usuário"
L["%1$s (%2$d) is not on the user-defined NPC list."] = "%1$s (%2$d) não está na lista de NPCs definida pelo usuário"
L["Added %1$s (%2$d) to the user-defined NPC list."] = "%1$s (%2$d) adicionado à lista de NPC definida pelo usuário"
L["Alerts"] = "Alertas"
L["BOTTOM"] = "Inferior"
L["BOTTOMLEFT"] = "Inferior Esquerdo"
L["BOTTOMRIGHT"] = "Inferior Direito "
L["CENTER"] = "Centro"
L["Completed Achievement Criteria"] = "Critério para conquista concluída"
L["Completed Quest Objectives"] = "Objetivos de Missões Concluídas"
--[[Translation missing --]]
--[[ L["Dead NPCs"] = "Dead NPCs"--]] 
L["Detection"] = "Detecção"
L["Drag to set the spawn point for targeting buttons."] = "Arraste para definir o ponto de nascimento para os botões alvo."
L["Duration"] = "Duração"
L["Hide Anchor"] = "Ocultar âncora"
L["Hide During Combat"] = "Ocultar Durante Combate"
L["Horizontal offset from the anchor point."] = "Deslocamento horizontal do ponto de ancoramento."
L["Ignore Mute"] = "Ignorar Mudo"
L["Interval"] = "Intervalo "
L["LEFT"] = "Esquerda"
L["NPCs"] = "NPCs "
L["Play alert sounds when sound is muted."] = "Tocar sons de alerta quando o som estiver mudo."
L["Predefined NPCs cannot be added to or removed from the user-defined NPC list."] = "NPCs predefinidos não podem serem adicionados ou removidos da lista definida pelo usuário."
L["Removed %1$s (%2$d) from the user-defined NPC list."] = "%1$s (%2$d) removido da lista de NPCs definida pelo usuário. "
L["Reset Position"] = "Redefinir Posição "
L["RIGHT"] = "Direita "
L["Screen Flash"] = "Piscar Tela"
L["Screen Location"] = "Localização da Tela "
L["Show Anchor"] = "Exibir Âncora"
L["Spawn Point"] = "Ponto de Nascimento"
L["The number of minutes a targeting button will exist before fading out."] = "Quantidade de minutos para o botão de alvo permanecer ativo antes de desaparecer."
L["The number of minutes before an NPC will be detected again."] = "Quantidade de minutos antes de um NPC ser detectado novamente."
L["TOP"] = "Topo "
L["TOPLEFT"] = "Topo Esquerdo "
L["TOPRIGHT"] = "Topo Direito "
L["Type the name of a Continent, Dungeon, or Zone, or the partial name of an NPC. Accepts Lua patterns."] = "Digite o nome do Continente, Masmorra, Zona ou um nome parcial de um NPC. Padrões LUA são aceitos."
L["Valid values are a numeric NPC ID, the word \"mouseover\" while you have your mouse cursor over an NPC, or the word \"target\" while you have an NPC set as your target."] = "A ID do NPC são valores numéricos válidos, a palavra \"mouseover\" é enquanto você passa o cursor em um NPC, ou a palavra \"alvo\" é enquanto você clicou em um NPC e definiu como seu alvo."
L["Vertical offset from the anchor point."] = "Deslocamento vertical do ponto de âncoragem."
L["X Offset"] = "Deslocamento X "
L["Y Offset"] = "Deslocamento Y "

